const R=['Common','Uncommon','Rare','Epic','Legendary'];
const SLOT_ORDER=['head','cape','neck','ammo','weapon','body','shield','legs','hands','feet','ring','tool'];
const SLOT_LABELS={head:'Head',cape:'Cape',neck:'Neck',ammo:'Ammo',weapon:'Weapon',body:'Body',shield:'Shield',legs:'Legs',hands:'Hands',feet:'Feet',ring:'Ring',tool:'Tool'};
const raw=[
['bronze_sword','Bronze Sword','Weapon','weapon','Common','⚔️',2],['steel_sword','Steel Sword','Weapon','weapon','Common','⚔️',4],['mith_scim','Mithril Scimitar','Weapon','weapon','Uncommon','🗡️',8],['rune_scim','Rune Scimitar','Weapon','weapon','Rare','🗡️',16],['dragon_scim','Dragon Scimitar','Weapon','weapon','Epic','🗡️',28],['whip','Abyssal Whip','Weapon','weapon','Legendary','🪢',44],
['bronze_helm','Bronze Full Helm','Armor','head','Common','🪖',2],['rune_helm','Rune Full Helm','Armor','head','Rare','🪖',10],['neitiznot','Helm of Neitiznot','Armor','head','Epic','🪖',18],['team_cape','Team Cape','Accessory','cape','Common','🧣',1],['firecape','Fire Cape','Accessory','cape','Legendary','🔥',18],['amulet_strength','Amulet of Strength','Accessory','neck','Common','📿',3],['glory','Amulet of Glory','Accessory','neck','Rare','📿',7],
['bronze_body','Bronze Platebody','Armor','body','Common','🛡️',2],['rune_body','Rune Platebody','Armor','body','Rare','🛡️',12],['fighter_torso','Fighter Torso','Armor','body','Epic','🛡️',20],['bandos','Bandos Chestplate','Armor','body','Legendary','🛡️',35],['wood_shield','Wooden Shield','Armor','shield','Common','🛡️',1],['rune_kite','Rune Kiteshield','Armor','shield','Rare','🛡️',10],['dragon_def','Dragon Defender','Armor','shield','Epic','🛡️',18],['bronze_legs','Bronze Platelegs','Armor','legs','Common','🦵',2],['rune_legs','Rune Platelegs','Armor','legs','Rare','🦵',10],['bandos_tassets','Bandos Tassets','Armor','legs','Legendary','🦵',28],['leather_gloves','Leather Gloves','Armor','hands','Common','🧤',1],['barrows_gloves','Barrows Gloves','Armor','hands','Epic','🧤',15],['leather_boots','Leather Boots','Armor','feet','Common','🥾',1],['dragon_boots','Dragon Boots','Armor','feet','Epic','🥾',14],['ring_dueling','Ring of Dueling','Accessory','ring','Common','💍',2],['berserker','Berserker Ring','Accessory','ring','Epic','💍',12],['bronze_arrows','Bronze Arrows','Ammo','ammo','Common','🏹',1],['rune_arrows','Rune Arrows','Ammo','ammo','Rare','🏹',8],
['bronze_axe','Bronze Axe','Tool','tool','Common','🪓',1],['rune_axe','Rune Axe','Tool','tool','Rare','🪓',8],['dragon_axe','Dragon Axe','Tool','tool','Epic','🪓',14],['bronze_pick','Bronze Pickaxe','Tool','tool','Common','⛏️',1],['rune_pick','Rune Pickaxe','Tool','tool','Rare','⛏️',8],['dragon_pick','Dragon Pickaxe','Tool','tool','Epic','⛏️',14],['net','Small Fishing Net','Tool','tool','Common','🎣',1],['harpoon','Harpoon','Tool','tool','Rare','🎣',7],
['goblin','Goblin','Monster',null,'Common','👺',0],['cow','Cow','Monster',null,'Common','🐄',0],['hill_giant','Hill Giant','Monster',null,'Uncommon','🧌',0],['green_dragon','Green Dragon','Monster',null,'Rare','🐉',0],['abyssal_demon','Abyssal Demon','Monster',null,'Epic','👹',0],['graardor','General Graardor','Boss',null,'Legendary','👑',0],['normal_tree','Normal Tree','Skilling',null,'Common','🌳',0],['oak_tree','Oak Tree','Skilling',null,'Common','🌲',0],['willow_tree','Willow Tree','Skilling',null,'Uncommon','🌿',0],['yew_tree','Yew Tree','Skilling',null,'Rare','🌲',0],['magic_tree','Magic Tree','Skilling',null,'Epic','✨',0],['copper_rock','Copper Rock','Skilling',null,'Common','🪨',0],['iron_rock','Iron Rock','Skilling',null,'Common','🪨',0],['coal_rock','Coal Rock','Skilling',null,'Uncommon','⬛',0],['mith_rock','Mithril Rock','Skilling',null,'Rare','💠',0],['runite_rock','Runite Rock','Skilling',null,'Epic','💎',0],['shrimp_spot','Net Fishing Spot','Skilling',null,'Common','🐟',0],['lobster_spot','Lobster Spot','Skilling',null,'Uncommon','🦞',0],['harpoon_spot','Harpoon Spot','Skilling',null,'Rare','🐠',0],['shark_spot','Shark Spot','Skilling',null,'Epic','🦈',0]
];
const C=raw.map(x=>({id:x[0],name:x[1],type:x[2],slot:x[3],rarity:x[4],icon:x[5],power:x[6]})),B=Object.fromEntries(C.map(c=>[c.id,c]));
const A=[['goblin','Combat',4,2],['cow','Combat',5,3],['hill_giant','Combat',14,12],['green_dragon','Combat',42,30],['abyssal_demon','Combat',90,55],['graardor','Combat',260,95],['normal_tree','Woodcutting',4,1],['oak_tree','Woodcutting',8,5],['willow_tree','Woodcutting',15,10],['yew_tree','Woodcutting',32,20],['magic_tree','Woodcutting',70,35],['copper_rock','Mining',4,1],['iron_rock','Mining',9,5],['coal_rock','Mining',17,10],['mith_rock','Mining',38,20],['runite_rock','Mining',85,36],['shrimp_spot','Fishing',4,1],['lobster_spot','Fishing',15,8],['harpoon_spot','Fishing',32,18],['shark_spot','Fishing',72,34]].map(x=>({id:x[0],kind:x[1],base:x[2],diff:x[3],...B[x[0]]}));
const packs={Beginner:{cost:500,n:3,o:[75,20,4.5,.5,0]},Bronze:{cost:1500,n:5,o:[65,25,8,1.8,.2]},Rune:{cost:5000,n:5,o:[38,36,19,6,1]},Dragon:{cost:15000,n:5,o:[18,32,30,16,4]},Raid:{cost:50000,n:7,o:[5,15,30,30,20]}};
const blankEq=()=>Object.fromEntries(SLOT_ORDER.map(k=>[k,null]));
const D={points:3000,owned:{bronze_sword:1,bronze_axe:1,bronze_pick:1,net:1,goblin:1,normal_tree:1,copper_rock:1,shrimp_spot:1},fragments:Object.fromEntries(R.map(r=>[r,0])),equipped:{...blankEq(),weapon:'bronze_sword',tool:'bronze_axe'},skills:{Combat:1,Woodcutting:1,Mining:1,Fishing:1},xp:{Combat:0,Woodcutting:0,Mining:0,Fishing:0},tab:'Home',packs:0,actions:0,idle:{activityId:null,lastTick:null,totalPoints:0}};
let s;try{const old=JSON.parse(localStorage.cardbound||'{}');s=Object.assign(structuredClone(D),old);const migrated=blankEq();if(old.equipped){if(old.equipped.weapon)migrated.weapon=old.equipped.weapon;if(old.equipped.tool)migrated.tool=old.equipped.tool;if(old.equipped.armor)migrated.body=old.equipped.armor;if(old.equipped.accessory){const c=B[old.equipped.accessory];migrated[c?.slot||'neck']=old.equipped.accessory}for(const k of SLOT_ORDER)if(old.equipped[k])migrated[k]=old.equipped[k]}s.equipped=migrated;s.fragments=Object.assign({},D.fragments,s.fragments||{});s.idle=Object.assign({},D.idle,s.idle||{});}catch{s=structuredClone(D)}
let bankFilters={type:'All',rarity:'All',status:'All',sort:'Name'};
const own=id=>s.owned[id]||0,save=()=>localStorage.cardbound=JSON.stringify(s),power=()=>5+Object.values(s.equipped).filter(Boolean).reduce((n,id)=>n+(B[id]?.power||0),0),need=a=>Math.max(1,Math.ceil(a.diff/2));
function roll(o){let x=Math.random()*100,n=0;for(let i=0;i<o.length;i++){n+=o[i];if(x<n)return R[i]}return R[0]}
function add(id){s.owned[id]=(s.owned[id]||0)+1}function nav(t){settleIdle(false);s.tab=t;save();render()}
function xp(k,n){s.xp[k]+=n;let req=20+s.skills[k]*s.skills[k]*8;while(s.xp[k]>=req){s.xp[k]-=req;s.skills[k]++;req=20+s.skills[k]*s.skills[k]*8}}
function rewardFor(a){let tool=Object.values(s.equipped).filter(Boolean).map(x=>B[x]).filter(x=>x?.type==='Tool').reduce((m,x)=>Math.max(m,x.power),0),mult=a.kind==='Combat'?Math.max(.65,1+power()/120-a.diff/150):1+tool/20;return Math.max(1,Math.round(a.base*mult))}
function cycleSeconds(a){return Math.max(4,Math.min(30,Math.round((a.kind==='Combat'?6:5)+a.diff/(a.kind==='Combat'?8:14))))}
function settleIdle(show){if(!s.idle.activityId||!s.idle.lastTick)return {points:0,cycles:0};const a=A.find(x=>x.id===s.idle.activityId);if(!a||!own(a.id)){s.idle={activityId:null,lastTick:null,totalPoints:s.idle.totalPoints||0};save();return {points:0,cycles:0}}const now=Date.now(),elapsed=Math.min(now-s.idle.lastTick,8*60*60*1000),cycles=Math.floor(elapsed/(cycleSeconds(a)*1000));if(cycles<1)return {points:0,cycles:0};const pts=cycles*rewardFor(a),xpGain=cycles*Math.max(2,Math.round(a.base/2));s.points+=pts;s.actions+=cycles;xp(a.kind,xpGain);s.idle.totalPoints=(s.idle.totalPoints||0)+pts;s.idle.lastTick+=cycles*cycleSeconds(a)*1000;save();if(show&&pts)toast(`While away: +${pts.toLocaleString()} points • ${cycles} actions`);return {points:pts,cycles}}
function startIdle(id){const a=A.find(x=>x.id===id);if(!a||!own(id))return;if(s.skills[a.kind]<need(a))return toast(`${a.kind} level ${need(a)} required`);settleIdle(false);s.idle={activityId:id,lastTick:Date.now(),totalPoints:s.idle.totalPoints||0};save();render();toast(`Now idling ${a.name}`)}
function stopIdle(){const a=A.find(x=>x.id===s.idle.activityId);const g=settleIdle(false);s.idle.activityId=null;s.idle.lastTick=null;save();render();toast(`${a?.name||'Activity'} stopped${g.points?` • +${g.points.toLocaleString()} points`:''}`)}
const cbIdleEngine=window.cbIdleEngine={
  cadence:0,timer:null,tickHandler:null,resumeHandler:null,
  settle(show=false){return settleIdle(show)},
  start(id){return startIdle(id)},
  stop(){return stopIdle()},
  configure({cadence,tick,resume}){
    if(this.timer)clearInterval(this.timer);
    this.cadence=cadence;
    this.tickHandler=tick;
    this.resumeHandler=resume||tick;
    this.timer=setInterval(()=>this.tick(),cadence);
    return this.timer;
  },
  tick(){return typeof this.tickHandler==='function'?this.tickHandler():undefined},
  resume(){return typeof this.resumeHandler==='function'?this.resumeHandler():undefined},
  snapshot(){return {cadence:this.cadence,hasTimer:!!this.timer,activeId:s.idle?.activityId||null}}
};
function openPack(n){settleIdle(false);let p=packs[n];if(s.points<p.cost)return toast('Not enough points');s.points-=p.cost;s.packs++;let q=[];for(let i=0;i<p.n;i++){let r=roll(p.o),pool=C.filter(c=>c.rarity===r),c=pool[Math.floor(Math.random()*pool.length)];add(c.id);q.push({...c,count:own(c.id)})}save();render();showPackOpening(n,q)}
function showPackOpening(name,cards){let idx=0,revealed=false;const m=document.createElement('div');m.className='modal pack-modal';document.body.append(m);function draw(){const c=cards[idx],remaining=cards.length-idx-1;m.innerHTML=`<div class="pack-stage"><div class="pack-topline"><b>${name} Pack</b><span>${idx+1}/${cards.length}</span></div><div class="stack-wrap" id="packTap">${Array.from({length:Math.min(4,remaining)}).map((_,i)=>`<div class="card-back ghost" style="transform:translate(${(i+1)*4}px,${-(i+1)*4}px) rotate(${(i%2?1:-1)*(i+1)}deg);z-index:${i}"></div>`).join('')}<div class="reveal-card ${revealed?'revealed':''} ${c.rarity}" style="z-index:10"><div class="card-face back-face"><div class="rune-mark">⚔️</div><div>GIELINOR</div><small>CARDBOUND</small><div class="tap-hint">Tap to reveal</div></div><div class="card-face front-face"><div class="rarity-tag">${c.rarity}</div><div class="big-icon">${c.icon}</div><h2>${c.name}</h2><div class="card-type">${c.type}${c.slot?` • ${SLOT_LABELS[c.slot]}`:''}</div>${c.power?`<div class="statline">Power +${c.power}</div>`:''}<div class="ownedline">Owned ×${c.count}</div><div class="tap-hint">${idx===cards.length-1?'Tap for results':'Tap for next card'}</div></div></div></div><div class="pack-progress">${cards.map((_,i)=>`<span class="${i<idx?'done':i===idx?'current':''}"></span>`).join('')}</div><button class="secondary" onclick="document.querySelector('.pack-modal')?.remove()">Skip opening</button></div>`;m.querySelector('#packTap').onclick=()=>{if(!revealed){revealed=true;draw();return}if(idx<cards.length-1){idx++;revealed=false;draw()}else results()}}function results(){m.innerHTML=`<div class="pack-results"><h2>${name} Pack Results</h2><div class="results-grid">${cards.map(c=>`<div class="result-card ${c.rarity}"><div class="icon">${c.icon}</div><b>${c.name}</b><div class="muted">${c.rarity} • ${c.type}<br>Owned ×${c.count}</div></div>`).join('')}</div><button class="primary wide" onclick="this.closest('.modal').remove()">Add to Bank</button></div>`}draw()}
function act(id){let a=A.find(x=>x.id===id);if(!own(id))return;if(s.skills[a.kind]<need(a))return toast(`${a.kind} level ${need(a)} required`);const n=rewardFor(a);s.points+=n;s.actions++;xp(a.kind,Math.max(2,Math.round(a.base/2)));save();render();toast(`+${n} points`)}
function isEquipped(id){return Object.values(s.equipped).includes(id)}function equip(id){const c=B[id];if(!c?.slot)return;s.equipped[c.slot]=id;save();render();toast(`${c.name} equipped`)}function unequip(slot){if(s.equipped[slot]){const n=B[s.equipped[slot]]?.name;s.equipped[slot]=null;save();render();toast(`${n||'Item'} unequipped`)}}
function shred(id){const c=B[id];if(own(id)<=1)return;s.owned[id]--;s.fragments[c.rarity]++;save();render();toast(`Shredded ${c.name}`)}function shredAllDuplicates(){let total=0;for(const c of C){const q=own(c.id);if(q>1){const d=q-1;s.owned[c.id]=1;s.fragments[c.rarity]+=d;total+=d}}save();render();toast(total?`Shredded ${total} duplicate card${total===1?'':'s'}`:'No duplicates to shred')}
function craft(r,t){if(s.fragments[r]<10)return;let p=C.filter(c=>c.rarity===r&&(t==='Any'||c.type===t||(t==='Equipment'&&c.slot)));if(!p.length)return toast('No matching cards');s.fragments[r]-=10;let c=p[Math.floor(Math.random()*p.length)];add(c.id);save();render();toast(`Crafted ${c.name}`)}
function toast(x){let e=document.createElement('div');e.className='toast';e.textContent=x;document.body.append(e);setTimeout(()=>e.remove(),1800)}function setBankFilter(k,v){bankFilters[k]=v;render()}
function filteredBank(){let arr=C.filter(c=>own(c.id)&&c.slot);if(bankFilters.type!=='All')arr=arr.filter(c=>c.type===bankFilters.type);if(bankFilters.rarity!=='All')arr=arr.filter(c=>c.rarity===bankFilters.rarity);if(bankFilters.status==='Equipped')arr=arr.filter(c=>isEquipped(c.id));if(bankFilters.status==='Unequipped')arr=arr.filter(c=>!isEquipped(c.id));if(bankFilters.status==='Duplicates')arr=arr.filter(c=>own(c.id)>1);arr.sort((a,b)=>bankFilters.sort==='Power'?b.power-a.power||a.name.localeCompare(b.name):bankFilters.sort==='Rarity'?R.indexOf(b.rarity)-R.indexOf(a.rarity)||a.name.localeCompare(b.name):bankFilters.sort==='Quantity'?own(b.id)-own(a.id)||a.name.localeCompare(b.name):bankFilters.sort==='Type'?a.type.localeCompare(b.type)||a.name.localeCompare(b.name):a.name.localeCompare(b.name));return arr}
function idlePanel(){if(!s.idle.activityId)return `<div class="panel idle-panel"><div><span class="eyebrow">IDLE ACTIVITY</span><h3>Nothing running</h3><p class="muted">Start any unlocked activity below. Progress continues for up to 8 hours while the app is closed.</p></div></div>`;const a=A.find(x=>x.id===s.idle.activityId),sec=cycleSeconds(a),r=rewardFor(a),pph=Math.floor(3600/sec*r);return `<div class="panel idle-panel active-idle"><div class="idle-main"><div class="idle-icon">${a.icon}</div><div><span class="eyebrow">CURRENTLY IDLING</span><h2>${a.name}</h2><div class="muted">${a.kind} • every ${sec}s • ~${pph.toLocaleString()} pts/hr</div></div></div><button class="danger" onclick="stopIdle()">Stop Activity</button></div>`}
const home=()=>`${idlePanel()}<div class="hero panel"><div><span class="eyebrow">ADVENTURE LOG</span><h2>${C.filter(c=>own(c.id)).length}/${C.length} cards discovered</h2><p class="muted">Open packs, unlock activities, equip stronger cards, and recycle duplicates into new pulls.</p></div><div class="hero-power">⚔️<b>${power()}</b><span>Power</span></div></div><div class="grid stats-grid"><div class="panel"><h3>⚔️ Combat</h3>Level ${s.skills.Combat}<br><span class="muted">Build power ${power()}</span></div><div class="panel"><h3>🪓 Skills</h3><span class="muted">WC ${s.skills.Woodcutting} • Mining ${s.skills.Mining} • Fishing ${s.skills.Fishing}</span></div><div class="panel"><h3>🎁 Packs</h3><b>${s.packs}</b></div><div class="panel"><h3>🏃 Activities</h3><b>${s.actions.toLocaleString()}</b></div></div>`;
const activities=()=>`${idlePanel()}${['Combat','Woodcutting','Mining','Fishing'].map(k=>`<div class="panel"><div class="section-head"><h2>${k}</h2><span class="pill">Lv ${s.skills[k]}</span></div><div class="grid">${A.filter(a=>a.kind===k).map(a=>{const active=s.idle.activityId===a.id;return `<div class="card ${own(a.id)?'':'locked'} ${a.rarity} ${active?'idle-selected':''}"><div class="icon">${a.icon}</div><b>${a.name}</b><div class="muted">${own(a.id)?`~${rewardFor(a)} pts/action • ${cycleSeconds(a)}s idle cycle • Req ${need(a)}`:'Card required'}</div><div class="activity-actions"><button ${own(a.id)?'':'disabled'} onclick="act('${a.id}')">Do Once</button><button class="${active?'danger':'primary'}" ${own(a.id)?'':'disabled'} onclick="${active?'stopIdle()':`startIdle('${a.id}')`}">${active?'Stop Idle':'Idle Here'}</button></div></div>`}).join('')}</div></div>`).join('')}`;
const store=()=>`<div class="panel pack-banner"><span class="eyebrow">PACK SHOP</span><h2>Choose your booster</h2><p class="muted">Tap through the stacked cards one at a time to reveal your pulls.</p></div><div class="grid pack-grid">${Object.entries(packs).map(([n,p])=>`<div class="card pack-card"><div class="pack-art">🎴</div><b>${n} Pack</b><div class="muted">${p.n} cards • ${p.cost.toLocaleString()} pts<br>Legendary ${p.o[4]}%</div><button class="primary" onclick="openPack('${n}')">Buy & Open</button></div>`).join('')}</div>`;
function equipmentSlots(){return `<div class="equipment-grid osrs-equip">${SLOT_ORDER.map(slot=>{const id=s.equipped[slot],c=id?B[id]:null;return `<button class="equip-slot ${c?c.rarity:''}" onclick="${c?`unequip('${slot}')`:''}"><span class="slot-label">${SLOT_LABELS[slot]}</span>${c?`<span class="equip-icon">${c.icon}</span><b>${c.name}</b><span class="muted">+${c.power} power • tap to unequip</span>`:`<span class="empty-slot">＋</span><span class="muted">Empty</span>`}</button>`}).join('')}</div>`}
const bank=()=>{const arr=filteredBank(),dupes=C.reduce((n,c)=>n+Math.max(0,own(c.id)-1),0);return `<div class="panel"><div class="section-head"><div><span class="eyebrow">LOADOUT</span><h2>Equipment • Power ${power()}</h2></div><span class="pill">${Object.values(s.equipped).filter(Boolean).length}/${SLOT_ORDER.length} equipped</span></div>${equipmentSlots()}</div><div class="panel"><div class="section-head"><div><span class="eyebrow">BANK</span><h2>Equipment Storage</h2></div><button class="danger" onclick="shredAllDuplicates()">Shred All Dupes (${dupes})</button></div><div class="bank-controls"><select onchange="setBankFilter('type',this.value)"><option ${bankFilters.type==='All'?'selected':''}>All</option><option ${bankFilters.type==='Weapon'?'selected':''}>Weapon</option><option ${bankFilters.type==='Armor'?'selected':''}>Armor</option><option ${bankFilters.type==='Accessory'?'selected':''}>Accessory</option><option ${bankFilters.type==='Ammo'?'selected':''}>Ammo</option><option ${bankFilters.type==='Tool'?'selected':''}>Tool</option></select><select onchange="setBankFilter('rarity',this.value)"><option ${bankFilters.rarity==='All'?'selected':''}>All</option>${R.map(r=>`<option ${bankFilters.rarity===r?'selected':''}>${r}</option>`).join('')}</select><select onchange="setBankFilter('status',this.value)"><option ${bankFilters.status==='All'?'selected':''}>All</option><option ${bankFilters.status==='Equipped'?'selected':''}>Equipped</option><option ${bankFilters.status==='Unequipped'?'selected':''}>Unequipped</option><option ${bankFilters.status==='Duplicates'?'selected':''}>Duplicates</option></select><select onchange="setBankFilter('sort',this.value)">${['Name','Power','Rarity','Quantity','Type'].map(v=>`<option ${bankFilters.sort===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="bank">${arr.length?arr.map(c=>`<div class="slot ${c.rarity} ${isEquipped(c.id)?'equipped-bank':''}" onclick="equip('${c.id}')">${isEquipped(c.id)?'<span class="equipped-badge">EQUIPPED</span>':''}<span class="bank-icon">${c.icon}</span><b>${c.name}</b><span class="muted">${SLOT_LABELS[c.slot]} • +${c.power}<br>Owned ×${own(c.id)}${own(c.id)>1?` • Dupes ${own(c.id)-1}`:''}</span>${own(c.id)>1?`<button class="mini danger" onclick="event.stopPropagation();shred('${c.id}')">Shred 1</button>`:''}</div>`).join(''):'<div class="empty-bank">No cards match these filters.</div>'}</div></div>`}
const collection=()=>`<div class="panel"><div class="section-head"><div><h2>Collection</h2><span class="muted">One copy is always preserved when shredding.</span></div><button class="danger" onclick="shredAllDuplicates()">Shred All Duplicates</button></div></div><div class="grid">${C.map(c=>`<div class="card ${c.rarity} ${own(c.id)?'':'locked'}"><div class="icon">${c.icon}</div><b>${own(c.id)?c.name:'???'}</b><div class="muted">${c.rarity} • ${c.type}${c.slot?` • ${SLOT_LABELS[c.slot]}`:''} • x${own(c.id)}</div>${own(c.id)>1?`<button class="danger" onclick="shred('${c.id}')">Shred duplicate</button>`:''}</div>`).join('')}</div>`;
const forge=()=>`<div class="panel"><h2>Fragment Forge</h2><span class="muted">10 same-rarity fragments craft a random card in your chosen category.</span></div>${R.map(r=>`<div class="panel"><h3>${r}: ${s.fragments[r]} fragments</h3><select id="${r}"><option>Any</option><option>Equipment</option><option>Weapon</option><option>Armor</option><option>Accessory</option><option>Ammo</option><option>Tool</option><option>Monster</option><option>Boss</option><option>Skilling</option></select> <button onclick="craft('${r}',document.getElementById('${r}').value)">Craft • 10</button></div>`).join('')}<div class="panel"><button onclick="s.points+=10000;save();render()">Developer +10,000 points</button> <button class="danger" onclick="if(confirm('Reset save?')){localStorage.removeItem('cardbound');location.reload()}">Reset</button></div>`;
function render(){let pages={Home:home,Activity:activities,Packs:store,Bank:bank,Collection:collection,Forge:forge},tabs=['Home','Activity','Packs','Bank','Collection','Forge'];document.getElementById('app').innerHTML=`<div class="app"><div class="top"><div class="brand">⚔️ <b>Gielinor: Cardbound</b></div><div class="wallet"><span class="pill">🪙 ${s.points.toLocaleString()} points</span><span class="pill">💥 Power ${power()}</span><span class="pill">🃏 ${C.filter(c=>own(c.id)).length}/${C.length}</span></div></div><div class="content">${pages[s.tab]()}</div><div class="tabs"><div>${tabs.map(t=>`<button class="tab ${s.tab===t?'active':''}" onclick="nav('${t}')">${{Home:'🏠',Activity:'⚔️',Packs:'🎁',Bank:'🏦',Collection:'🃏',Forge:'🔥'}[t]}<br>${t}</button>`).join('')}</div></div></div>`}
const away=cbIdleEngine.settle(false);save();render();if(away.points)setTimeout(()=>toast(`While away: +${away.points.toLocaleString()} points • ${away.cycles} actions`),250);cbIdleEngine.configure({cadence:30000,tick:()=>{if(s.idle.activityId){const g=cbIdleEngine.settle(false);if(g.cycles)render()}},resume:()=>{if(s.idle.activityId){const g=cbIdleEngine.settle(false);if(g.cycles){render();toast(`Idle progress: +${g.points.toLocaleString()} points`)}}}});document.addEventListener('visibilitychange',()=>{if(!document.hidden)cbIdleEngine.resume()});
