// Core render fix: bypass immutable legacy page bindings and render the current UI directly.
(function(){
const STYLES=['Melee','Ranged','Magic'];
if(!window.cbCoreUi)window.cbCoreUi={activityRoot:null,skill:null};
const styleIcon=st=>st==='Melee'?'⚔️':st==='Ranged'?'🏹':'✨';
const equippedStyle=()=>B[s.equipped.weapon]?.combatStyle||'Melee';
const img=(c,cls='cb-activity-icon')=>typeof cardImage==='function'?cardImage(c,cls):(typeof cb2Img==='function'?cb2Img(c,cls):`<span class="icon">${c.icon||'?'}</span>`);
const idle=()=>typeof cbIdlePanel==='function'?cbIdlePanel():(typeof idlePanel==='function'?idlePanel():'');
function stylePowerLocal(st){return 5+Object.entries(s.equipped).filter(([slot,id])=>id&&slot!=='tool').reduce((n,[slot,id])=>{const c=B[id];if(!c)return n;const same=(c.combatStyle||'Melee')===st;const foil=(s.equippedFoil&&s.equippedFoil[slot])?1.05:1;return n+(c.power||0)*(same?1:.25)*foil},0)}
window.cbSetActivityRoot=function(root){cbCoreUi.activityRoot=root;cbCoreUi.skill=null;render()};
window.cbSetSkill=function(skill){cbCoreUi.skill=skill;render()};
window.cbBackActivities=function(){cbCoreUi.activityRoot=null;cbCoreUi.skill=null;render()};
function homeCore(){return `${idle()}<div class="hero panel"><div><span class="eyebrow">ADVENTURE LOG</span><h2>${C.filter(c=>own(c.id)).length}/${C.length} cards discovered</h2><p class="muted">Build separate Melee, Ranged, and Magic progression while unlocking Slayer and skilling activities.</p></div><div class="hero-power">⚔️<b>${Math.round(power())}</b><span>Total Power</span></div></div><div class="cbcore-combat-grid">${STYLES.map(st=>`<button class="panel cbcore-style" onclick="s.tab='Activity';cbSetActivityRoot('${st}')"><span class="cbcore-style-icon">${styleIcon(st)}</span><h3>${st}</h3><b>Level ${s.skills[st]||1}</b><small>Power ${Math.round(stylePowerLocal(st))}</small></button>`).join('')}</div><div class="grid stats-grid"><div class="panel"><h3>☠ Slayer</h3>Level ${s.skills.Slayer||1}</div><div class="panel"><h3>🪓 Woodcutting</h3>Level ${s.skills.Woodcutting||1}</div><div class="panel"><h3>⛏ Mining</h3>Level ${s.skills.Mining||1}</div><div class="panel"><h3>🎣 Fishing</h3>Level ${s.skills.Fishing||1}</div><div class="panel"><h3>🎁 Packs</h3><b>${s.packs}</b></div><div class="panel"><h3>🏃 Actions</h3><b>${s.actions.toLocaleString()}</b></div></div>`}
function activityRoot(){return `${idle()}<div class="panel"><span class="eyebrow">ACTIVITY</span><h2>Choose a category</h2><div class="cbcore-root-grid">${STYLES.map(st=>`<button class="cbcore-root-card" onclick="cbSetActivityRoot('${st}')"><span>${styleIcon(st)}</span><b>${st}</b><small>Level ${s.skills[st]||1}</small></button>`).join('')}<button class="cbcore-root-card" onclick="cbSetActivityRoot('Slayer')"><span>☠️</span><b>Slayer</b><small>Level ${s.skills.Slayer||1}</small></button><button class="cbcore-root-card" onclick="cbSetActivityRoot('Skilling')"><span>🛠️</span><b>Skilling</b><small>Choose a skill</small></button></div></div>`}
function monsterCards(st,kind='Combat'){const current=equippedStyle();const acts=A.filter(a=>a.kind===kind);return `${idle()}<div class="panel"><button class="secondary" onclick="cbBackActivities()">← Activities</button><div class="section-head"><div><span class="eyebrow">${st.toUpperCase()}</span><h2>${st}${kind==='Slayer'?'':' Combat'}</h2></div><span class="pill">Lv ${s.skills[st]||1}</span></div>${kind==='Combat'?`<p class="muted">${current===st?`Your equipped weapon is using ${st}.`:`Equip a ${st.toLowerCase()} weapon in Bank to train this style.`}</p>`:''}<div class="cb2-activity-list">${acts.map(a=>{const unlocked=!!own(a.id),meets=typeof cb2Meets==='function'?cb2Meets(a):true,usable=unlocked&&meets&&(kind==='Slayer'||current===st),active=s.idle.activityId===a.id;return `<div class="cb2-activity-card ${a.rarity} ${unlocked?'':'locked'} ${active?'idle-selected':''}">${img(a)}<div class="cb2-grow"><b>${a.name}</b><div class="muted">${a.hp||'?'} HP • ${rewardFor(a)} pts • ${cycleSeconds(a)}s<br>${unlocked?(meets?'Card unlocked':'Requirements not met'):'Card required'}</div></div><div class="cb2-actions"><button ${usable?'':'disabled'} onclick="act('${a.id}')">Once</button><button class="${active?'danger':'primary'}" ${usable?'':'disabled'} onclick="${active?'stopIdle()':`startIdle('${a.id}')`}">${active?'Stop':'Idle'}</button></div></div>`}).join('')}</div></div>`}
function skillingRoot(){return `${idle()}<div class="panel"><button class="secondary" onclick="cbBackActivities()">← Activities</button><span class="eyebrow">SKILLING</span><h2>Choose a skill</h2><div class="cbcore-root-grid">${['Woodcutting','Mining','Fishing'].map(sk=>`<button class="cbcore-root-card" onclick="cbSetSkill('${sk}')"><span>${sk==='Woodcutting'?'🪓':sk==='Mining'?'⛏️':'🎣'}</span><b>${sk}</b><small>Level ${s.skills[sk]||1}</small></button>`).join('')}</div></div>`}
function skillList(sk){const acts=A.filter(a=>a.kind===sk);return `${idle()}<div class="panel"><button class="secondary" onclick="cbSetSkill(null)">← Skills</button><div class="section-head"><h2>${sk}</h2><span class="pill">Lv ${s.skills[sk]||1}</span></div><div class="cb2-activity-list">${acts.map(a=>{const unlocked=!!own(a.id),meets=typeof cb2Meets==='function'?cb2Meets(a):true,active=s.idle.activityId===a.id;return `<div class="cb2-activity-card ${a.rarity} ${unlocked?'':'locked'} ${active?'idle-selected':''}">${img(a)}<div class="cb2-grow"><b>${a.name}</b><div class="muted">${unlocked?(meets?`${rewardFor(a)} pts • ${cycleSeconds(a)}s • ${a.reqSkill||sk} ${a.reqLevel||1}`:'Requirements not met'):'Card required'}</div></div><div class="cb2-actions"><button ${unlocked&&meets?'':'disabled'} onclick="act('${a.id}')">Once</button><button class="${active?'danger':'primary'}" ${unlocked&&meets?'':'disabled'} onclick="${active?'stopIdle()':`startIdle('${a.id}')`}">${active?'Stop':'Idle'}</button></div></div>`}).join('')}</div></div>`}
function activityCore(){const r=cbCoreUi.activityRoot;if(!r)return activityRoot();if(STYLES.includes(r))return monsterCards(r,'Combat');if(r==='Slayer')return monsterCards('Slayer','Slayer');if(r==='Skilling')return cbCoreUi.skill?skillList(cbCoreUi.skill):skillingRoot();return activityRoot()}
const packLooks={Beginner:{icon:'📜',sigil:'I',name:'Beginner',tag:'Adventurer Cache'},Bronze:{icon:'🛡️',sigil:'B',name:'Bronze',tag:'Forged Booster'},Rune:{icon:'💠',sigil:'R',name:'Rune',tag:'Runic Booster'},Dragon:{icon:'🐉',sigil:'D',name:'Dragon',tag:'Dragonfire Booster'},Raid:{icon:'👑',sigil:'★',name:'Raid',tag:'Ancient Raid Relic'}};
function storeCore(){return `<div class="panel pack-banner"><span class="eyebrow">PACK SHOP</span><h2>Choose your booster</h2><p class="muted">Every tier has its own visual identity, with higher tiers becoming progressively more prestigious.</p></div><div class="cbcore-pack-grid">${Object.entries(packs).map(([n,p])=>{const m=packLooks[n]||packLooks.Beginner;return `<div class="cbcore-pack pack-${n}"><div class="cbcore-pack-icon"><span class="pack-sigil">${m.sigil}</span><span class="pack-symbol">${m.icon}</span></div><span class="eyebrow">${m.tag}</span><h3>${m.name} Pack</h3><div class="muted">${p.n} cards • ${p.cost.toLocaleString()} pts<br>Legendary ${p.o[4]}%</div><button class="primary wide" onclick="openPack('${n}')">Buy & Open</button></div>`}).join('')}</div>`}
const legacyBank=bank,legacyCollection=collection,legacyForge=forge;
render=function(){const pages={Home:homeCore,Activity:activityCore,Packs:storeCore,Bank:legacyBank,Collection:(typeof cbCollection==='function'?cbCollection:legacyCollection),Forge:legacyForge},tabs=['Home','Activity','Packs','Bank','Collection','Forge'];document.getElementById('app').innerHTML=`<div class="app"><div class="top"><div class="brand">⚔️ <b>Gielinor: Cardbound</b></div><div class="wallet"><span class="pill">🪙 ${s.points.toLocaleString()} points</span><span class="pill">💥 Power ${Math.round(power())}</span><span class="pill">🃏 ${C.filter(c=>own(c.id)).length}/${C.length}</span></div></div><div class="content">${pages[s.tab]()}</div><div class="tabs"><div>${tabs.map(t=>`<button class="tab ${s.tab===t?'active':''}" onclick="nav('${t}')">${{Home:'🏠',Activity:'⚔️',Packs:'🎁',Bank:'🏦',Collection:'🃏',Forge:'🔥'}[t]}<br>${t}</button>`).join('')}</div></div></div>`};
cbCoreUi.activityRoot=null;cbCoreUi.skill=null;save();render();
})();