// Core render owner: single page shell/router plus authoritative Activity/Skilling/Sailing navigation.
(function(){
const STYLES=['Melee','Ranged','Magic'];
if(!window.cbCoreUi)window.cbCoreUi={activityRoot:null,skill:null};
if(!window.cbCoreSailing)window.cbCoreSailing={category:null};
const pageRenderers=Object.create(null);
window.cbRegisterPage=function(name,renderer){
  if(!name||typeof renderer!=='function')return false;
  pageRenderers[name]=renderer;
  return true;
};
window.cbResolvePage=function(name){return pageRenderers[name]||pageRenderers.Home};
window.cbRegisteredPages=function(){return Object.freeze(Object.keys(pageRenderers))};
const styleIcon=st=>st==='Melee'?'⚔️':st==='Ranged'?'🏹':'✨';
const equippedStyle=()=>B[s.equipped.weapon]?.combatStyle||'Melee';
const img=(c,cls='cb-activity-icon')=>typeof cardImage==='function'?cardImage(c,cls):(typeof cb2Img==='function'?cb2Img(c,cls):`<span class="icon">${c.icon||'?'}</span>`);
const idle=()=>typeof cbIdlePanel==='function'?cbIdlePanel():(typeof idlePanel==='function'?idlePanel():'');
function stylePowerLocal(st){return 5+Object.entries(s.equipped).filter(([slot,id])=>id&&slot!=='tool').reduce((n,[slot,id])=>{const c=B[id];if(!c)return n;const same=(c.combatStyle||'Melee')===st;const foil=(s.equippedFoil&&s.equippedFoil[slot])?1.05:1;return n+(c.power||0)*(same?1:.25)*foil},0)}
window.cbSetActivityRoot=function(root){cbCoreUi.activityRoot=root;cbCoreUi.skill=null;cbCoreSailing.category=null;render()};
window.cbSetSkill=function(skill){cbCoreUi.activityRoot='Skilling';cbCoreUi.skill=skill;cbCoreSailing.category=null;if(skill==='Sailing')s.tab='Activity';save();render()};
window.cbOpenSailing=function(){return cbSetSkill('Sailing')};
window.cbBackActivities=function(){cbCoreUi.activityRoot=null;cbCoreUi.skill=null;cbCoreSailing.category=null;render()};
window.cbSailingCategory=function(cat){cbCoreSailing.category=cat;render()};
window.cbSailingBack=function(){if(cbCoreSailing.category){cbCoreSailing.category=null;render();return;}cbSetSkill(null)};
// Compatibility aliases retained for historical inline handlers.
window.cb33SailingCategory=window.cbSailingCategory;
window.cb33SailingBack=window.cbSailingBack;
function levelRow(icon,name,level,onClick,sub=''){return `<button class="cb23-skill-row" onclick="${onClick}"><span class="cb23-icon">${icon}</span><span class="cb23-name"><b>${name}</b>${sub?`<small>${sub}</small>`:''}</span><span class="cb23-level">Lv ${level||1}</span><span class="cb23-arrow">›</span></button>`}
function homeCore(){const facilities=C.filter(c=>c.type==='Sailing Facility'),ownedFacilities=facilities.filter(c=>own(c.id)).length;const combat=`<section class="panel cb23-group"><div class="cb23-group-head"><div><span class="eyebrow">COMBAT</span><h2>Combat Skills</h2></div><span class="cb23-group-icon">⚔️</span></div><div class="cb23-list">${levelRow('⚔️','Melee',s.skills.Melee,"cbHomeGoRoot('Melee')",'Close-range combat')}${levelRow('🏹','Ranged',s.skills.Ranged,"cbHomeGoRoot('Ranged')",'Bows, crossbows & thrown weapons')}${levelRow('✨','Magic',s.skills.Magic,"cbHomeGoRoot('Magic')",'Staves, spells & magic weapons')}${levelRow('☠️','Slayer',s.skills.Slayer,"cbHomeGoRoot('Slayer')",'Task and monster progression')}</div></section>`;const skilling=`<section class="panel cb23-group"><div class="cb23-group-head"><div><span class="eyebrow">SKILLING</span><h2>Gathering & Sailing</h2></div><span class="cb23-group-icon">🛠️</span></div><div class="cb23-list">${levelRow('🪓','Woodcutting',s.skills.Woodcutting,"cbHomeGoSkill('Woodcutting')")}${levelRow('⛏️','Mining',s.skills.Mining,"cbHomeGoSkill('Mining')")}${levelRow('🎣','Fishing',s.skills.Fishing,"cbHomeGoSkill('Fishing')")}${levelRow('⛵','Sailing',s.skills.Sailing,"cbHomeGoSkill('Sailing')",`${ownedFacilities}/${facilities.length} facilities unlocked`)}</div></section>`;const progress=`<section class="panel cb23-progress"><div><span class="eyebrow">PROGRESS</span><h3>Adventure Summary</h3></div><div class="cb23-progress-grid"><div><b>${s.packs||0}</b><small>Packs opened</small></div><div><b>${(s.actions||0).toLocaleString()}</b><small>Actions</small></div><div><b>${C.filter(c=>own(c.id)).length}/${C.length}</b><small>Cards</small></div><div><b>${s.foils?C.filter(c=>(s.foils[c.id]||0)>0).length:0}</b><small>Foils</small></div></div></section>`;return `${idle()}<div class="hero panel"><div><span class="eyebrow">ADVENTURE LOG</span><h2>${C.filter(c=>own(c.id)).length}/${C.length} cards discovered</h2><p class="muted">Build separate Melee, Ranged, and Magic progression while unlocking Slayer and skilling activities.</p></div><div class="hero-power">⚔️<b>${Math.round(power())}</b><span>Total Power</span></div></div><div class="cb23-home-groups">${combat}${skilling}</div>${progress}`}
function activityRoot(){return `${idle()}<div class="panel"><span class="eyebrow">ACTIVITY</span><h2>Choose a category</h2><div class="cbcore-root-grid">${STYLES.map(st=>`<button class="cbcore-root-card" onclick="cbSetActivityRoot('${st}')"><span>${styleIcon(st)}</span><b>${st}</b><small>Level ${s.skills[st]||1}</small></button>`).join('')}<button class="cbcore-root-card" onclick="cbSetActivityRoot('Slayer')"><span>☠️</span><b>Slayer</b><small>Level ${s.skills.Slayer||1}</small></button><button class="cbcore-root-card" onclick="cbSetActivityRoot('Skilling')"><span>🛠️</span><b>Skilling</b><small>Choose a skill</small></button></div></div>`}
function monsterCards(st,kind='Combat'){const current=equippedStyle();const acts=A.filter(a=>a.kind===kind);return `${idle()}<div class="panel"><button class="secondary" onclick="cbBackActivities()">← Activities</button><div class="section-head"><div><span class="eyebrow">${st.toUpperCase()}</span><h2>${st}${kind==='Slayer'?'':' Combat'}</h2></div><span class="pill">Lv ${s.skills[st]||1}</span></div>${kind==='Combat'?`<p class="muted">${current===st?`Your equipped weapon is using ${st}.`:`Equip a ${st.toLowerCase()} weapon in Bank to train this style.`}</p>`:''}<div class="cb2-activity-list">${acts.map(a=>{const unlocked=!!own(a.id),meets=typeof cb2Meets==='function'?cb2Meets(a):true,usable=unlocked&&meets&&(kind==='Slayer'||current===st),active=s.idle.activityId===a.id;return `<div class="cb2-activity-card ${a.rarity} ${unlocked?'':'locked'} ${active?'idle-selected':''}">${img(a)}<div class="cb2-grow"><b>${a.name}</b><div class="muted">${a.hp||'?'} HP • ${rewardFor(a)} pts • ${cycleSeconds(a)}s<br>${unlocked?(meets?'Card unlocked':'Requirements not met'):'Card required'}</div></div><div class="cb2-actions"><button ${usable?'':'disabled'} onclick="act('${a.id}')">Once</button><button class="${active?'danger':'primary'}" ${usable?'':'disabled'} onclick="${active?'stopIdle()':`startIdle('${a.id}')`}">${active?'Stop':'Idle'}</button></div></div>`}).join('')}</div></div>`}
function skillingRoot(){const skills=[['Woodcutting','🪓'],['Mining','⛏️'],['Fishing','🎣'],['Sailing','⛵']];return `${idle()}<div class="panel"><button class="secondary" onclick="cbBackActivities()">← Activities</button><span class="eyebrow">SKILLING</span><h2>Choose a skill</h2><div class="cbcore-root-grid">${skills.map(([sk,ic])=>`<button class="cbcore-root-card" onclick="cbSetSkill('${sk}')"><span>${ic}</span><b>${sk}</b><small>Level ${s.skills[sk]||1}</small></button>`).join('')}</div></div>`}
function skillList(sk){const acts=A.filter(a=>a.kind===sk);return `${idle()}<div class="panel"><button class="secondary" onclick="cbSetSkill(null)">← Skills</button><div class="section-head"><h2>${sk}</h2><span class="pill">Lv ${s.skills[sk]||1}</span></div><div class="cb2-activity-list">${acts.map(a=>{const unlocked=!!own(a.id),meets=typeof cb2Meets==='function'?cb2Meets(a):true,active=s.idle.activityId===a.id;return `<div class="cb2-activity-card ${a.rarity} ${unlocked?'':'locked'} ${active?'idle-selected':''}">${img(a)}<div class="cb2-grow"><b>${a.name}</b><div class="muted">${unlocked?(meets?`${rewardFor(a)} pts • ${cycleSeconds(a)}s • ${a.reqSkill||sk} ${a.reqLevel||1}`:'Requirements not met'):'Card required'}</div></div><div class="cb2-actions"><button ${unlocked&&meets?'':'disabled'} onclick="act('${a.id}')">Once</button><button class="${active?'danger':'primary'}" ${unlocked&&meets?'':'disabled'} onclick="${active?'stopIdle()':`startIdle('${a.id}')`}">${active?'Stop':'Idle'}</button></div></div>`}).join('')}</div></div>`}
function sailingBody(){const lv=s.skills.Sailing||1;if(!cbCoreSailing.category){const cats=window.cbSailingCategories||['Port Tasks','Charting','Salvaging','Trawling','Combat','Trials'];const facilities=C.filter(c=>c.type==='Sailing Facility');const owned=facilities.filter(c=>own(c.id)).length;const icons={'Port Tasks':'📜',Charting:'🗺️',Salvaging:'🪝',Trawling:'🐟',Combat:'💥',Trials:'🏁'};return `${idle()}<div class="panel"><button class="secondary" onclick="cbSailingBack()">← Skills</button><span class="eyebrow">SKILLING • SAILING</span><div class="section-head"><h2>Sailing</h2><span class="pill">Lv ${lv}</span></div><p class="muted">Choose a Sailing method.</p><div class="cb-sailing-categories">${cats.map(cat=>`<button class="cb-sailing-category" onclick="cbSailingCategory('${cat}')"><span>${icons[cat]||'⚓'}</span><b>${cat}</b><small>${A.filter(a=>a.kind==='Sailing'&&a.sailingCategory===cat).length} actions</small></button>`).join('')}</div></div><div class="panel"><span class="eyebrow">SHIP FACILITIES</span><h3>${owned}/${facilities.length} unlocked</h3></div>`;}const cat=cbCoreSailing.category,acts=A.filter(a=>a.kind==='Sailing'&&a.sailingCategory===cat);return `${idle()}<div class="panel"><button class="secondary" onclick="cbSailingBack()">← Sailing</button><span class="eyebrow">SAILING • ${cat.toUpperCase()}</span><div class="section-head"><h2>${cat}</h2><span class="pill">Lv ${lv}</span></div><div class="cb2-activity-list">${acts.map(a=>{const unlocked=own(a.id)>0;const meets=typeof cbSailingReqMet==='function'?cbSailingReqMet(a):lv>=(a.reqLevel||1);const active=s.idle?.activityId===a.id;const req=(a.reqCards||[]).map(id=>B[id]?.name||id).join(', ');let pts='?';let secs='?';try{pts=rewardFor(a);secs=cycleSeconds(a)}catch{}return `<div class="cb2-activity-card ${a.rarity} ${unlocked?'':'locked'} ${active?'idle-selected':''}">${img(a)}<div class="cb2-grow"><b>${a.name}</b><div class="muted">Sailing ${a.reqLevel||1} • ${pts} pts • ${secs}s${req?`<br>Facility: ${req}`:''}<br>${!unlocked?'Activity card required':meets?'Ready':'Missing facility/level requirement'}</div></div><div class="cb2-actions"><button ${unlocked&&meets?'':'disabled'} onclick="act('${a.id}')">Once</button><button ${unlocked&&meets?'':'disabled'} class="${active?'danger':'primary'}" onclick="${active?'stopIdle()':`startIdle('${a.id}')`}">${active?'Stop':'Idle'}</button></div></div>`}).join('')||'<p class="muted">No activities found.</p>'}</div></div>`}
function activityCore(){const r=cbCoreUi.activityRoot;if(!r)return activityRoot();if(STYLES.includes(r))return monsterCards(r,'Combat');if(r==='Slayer')return monsterCards('Slayer','Slayer');if(r==='Skilling'){if(!cbCoreUi.skill)return skillingRoot();return cbCoreUi.skill==='Sailing'?sailingBody():skillList(cbCoreUi.skill)}return activityRoot()}
const packLooks={Beginner:{icon:'📜',sigil:'I',name:'Beginner',tag:'Adventurer Cache'},Bronze:{icon:'🛡️',sigil:'B',name:'Bronze',tag:'Forged Booster'},Rune:{icon:'💠',sigil:'R',name:'Rune',tag:'Runic Booster'},Dragon:{icon:'🐉',sigil:'D',name:'Dragon',tag:'Dragonfire Booster'},Raid:{icon:'👑',sigil:'★',name:'Raid',tag:'Ancient Raid Relic'}};
function storeCore(){return `<div class="panel pack-banner"><span class="eyebrow">PACK SHOP</span><h2>Choose your booster</h2><p class="muted">Every tier has its own visual identity, with higher tiers becoming progressively more prestigious.</p></div><div class="cbcore-pack-grid">${Object.entries(packs).map(([n,p])=>{const m=packLooks[n]||packLooks.Beginner;return `<div class="cbcore-pack pack-${n}"><div class="cbcore-pack-icon"><span class="pack-sigil">${m.sigil}</span><span class="pack-symbol">${m.icon}</span></div><span class="eyebrow">${m.tag}</span><h3>${m.name} Pack</h3><div class="muted">${p.n} cards • ${p.cost.toLocaleString()} pts<br>Legendary ${p.o[4]}%</div><button class="primary wide" onclick="openPack('${n}')">Buy & Open</button></div>`}).join('')}</div>`}
const legacyBank=bank,legacyCollection=collection,legacyForge=forge;
cbRegisterPage('Home',homeCore);
cbRegisterPage('Activity',activityCore);
cbRegisterPage('Packs',storeCore);
cbRegisterPage('Bank',legacyBank);
cbRegisterPage('Collection',typeof cbCollection==='function'?cbCollection:legacyCollection);
cbRegisterPage('Forge',legacyForge);
render=function(){const tabs=['Home','Activity','Packs','Bank','Collection','Forge'],renderer=cbResolvePage(s.tab);document.getElementById('app').innerHTML=`<div class="app"><div class="top"><div class="brand">⚔️ <b>Gielinor: Cardbound</b></div><div class="wallet"><span class="pill">🪙 ${s.points.toLocaleString()} points</span><span class="pill">💥 Power ${Math.round(power())}</span><span class="pill">🃏 ${C.filter(c=>own(c.id)).length}/${C.length}</span></div></div><div class="content">${renderer()}</div><div class="tabs"><div>${tabs.map(t=>`<button class="tab ${s.tab===t?'active':''}" onclick="nav('${t}')">${{Home:'🏠',Activity:'⚔️',Packs:'🎁',Bank:'🏦',Collection:'🃏',Forge:'🔥'}[t]}<br>${t}</button>`).join('')}</div></div></div>`};
cbCoreUi.activityRoot=null;cbCoreUi.skill=null;cbCoreSailing.category=null;save();render();
})();
