// Final image layer: use RuneLite item sprites and explicit OSRS Wiki images everywhere.
(function(){
const ITEM='https://static.runelite.net/cache/item/icon/';
const WIKI='https://oldschool.runescape.wiki/Special:FilePath/';
const imageOverrides={
chicken:'Chicken.png',man:'Man.png',woman:'Woman.png',imp:'Imp.png',minotaur:'Minotaur.png',wolf:'Wolf.png',scorpion:'Scorpion.png',dark_wizard:'Dark_wizard.png',hobgoblin:'Hobgoblin.png',zombie:'Zombie.png',skeleton:'Skeleton.png',ogre:'Ogre.png',ice_warrior:'Ice_warrior.png',ankou:'Ankou.png',fire_giant:'Fire_giant.png',hellhound:'Hellhound.png',greater_demon:'Greater_demon.png',black_dragon:'Black_dragon.png',brutal_black_dragon:'Brutal_black_dragon.png',skeletal_wyvern:'Skeletal_Wyvern.png',dagannoth:'Dagannoth.png',mutated_bloodveld:'Mutated_Bloodveld.png',
obor:'Obor.png',bryophyta:'Bryophyta.png',scurrius:'Scurrius.png',deranged_archaeologist:'Deranged_archaeologist.png',crazy_archaeologist:'Crazy_archaeologist.png',chaos_fanatic:'Chaos_Fanatic.png',chaos_elemental:'Chaos_Elemental.png',giant_mole:'Giant_Mole.png',kalphite_queen:'Kalphite_Queen.png',dagannoth_rex:'Dagannoth_Rex.png',dagannoth_prime:'Dagannoth_Prime.png',dagannoth_supreme:'Dagannoth_Supreme.png',commander_zilyana:'Commander_Zilyana.png',kree_arra:'Kree%27arra.png',kril_tsutsaroth:'K%27ril_Tsutsaroth.png',corporeal_beast:'Corporeal_Beast.png',cerberus:'Cerberus.png',thermonuclear_smoke_devil:'Thermonuclear_smoke_devil.png',grotesque_guardians:'Dusk.png',skotizo:'Skotizo.png',hespori:'Hespori.png',gauntlet:'Crystalline_Hunllef.png',corrupted_hunllef:'Corrupted_Hunllef.png',nightmare:'The_Nightmare.png',phosani:'Phosani%27s_Nightmare.png',nex:'Nex.png',duke_sucellus:'Duke_Sucellus.png',vardorvis:'Vardorvis.png',leviathan:'The_Leviathan.png',whisperer:'The_Whisperer.png',araxxor:'Araxxor.png',amoxliatl:'Amoxliatl.png',hueycoatl:'The_Hueycoatl.png',royal_titans:'Royal_Titans.png',jad:'TzTok-Jad.png',zuk:'TzKal-Zuk.png',
crawling_hand:'Crawling_hand.png',banshee:'Banshee.png',rock_slug:'Rock_slug.png',cockatrice:'Cockatrice.png',pyrefiend:'Pyrefiend.png',basilisk:'Basilisk.png',fever_spider:'Fever_spider.png',infernal_mage:'Infernal_mage.png',bloodveld:'Bloodveld.png',jelly:'Jelly.png',turoth:'Turoth.png',cave_horror:'Cave_horror.png',aberrant_spectre:'Aberrant_spectre.png',dust_devil:'Dust_devil.png',kurask:'Kurask.png',gargoyle:'Gargoyle.png',nechryael:'Nechryael.png',abyssal_demon:'Abyssal_demon.png',dark_beast:'Dark_beast.png',smoke_devil:'Smoke_devil.png',alchemical_hydra:'Alchemical_Hydra.png',
normal_tree:'Tree.png',oak_tree:'Oak_tree.png',willow_tree:'Willow_tree.png',teak_tree:'Teak_tree.png',maple_tree:'Maple_tree.png',mahogany_tree:'Mahogany_tree.png',yew_tree:'Yew_tree.png',magic_tree:'Magic_tree.png',redwood_tree:'Redwood.png',achey_tree:'Achey_tree.png',arctic_pine:'Arctic_pine.png',sulliuscep:'Sulliuscep.png',blisterwood:'Blisterwood_tree.png',hollow_tree:'Hollow_tree.png',
copper_rock:'Copper_rock.png',tin_rock:'Tin_rock.png',iron_rock:'Iron_rock.png',coal_rock:'Coal_rock.png',gold_rock:'Gold_rock.png',mith_rock:'Mithril_rock.png',adamant_rock:'Adamantite_rock.png',runite_rock:'Runite_rock.png',amethyst:'Amethyst_crystals.png',clay_rock:'Clay_rock.png',silver_rock:'Silver_rock.png',gem_rock:'Gem_rock.png',sandstone:'Sandstone_rock.png',granite_rock:'Granite_rock.png',volcanic_mine:'Volcanic_mine.png',
shrimp_spot:'Fishing_spot.png',bait_spot:'Fishing_spot.png',trout_spot:'Fishing_spot.png',lobster_spot:'Fishing_spot.png',harpoon_spot:'Fishing_spot.png',monkfish_spot:'Fishing_spot.png',shark_spot:'Fishing_spot.png',angler_spot:'Fishing_spot.png',sardine_spot:'Fishing_spot.png',salmon_spot:'Fishing_spot.png',tuna_spot:'Fishing_spot.png',swordfish_spot:'Fishing_spot.png',karambwan_spot:'Karambwan_fishing_spot.png',dark_crab_spot:'Fishing_spot.png',sacred_eel_spot:'Fishing_spot.png',infernal_eel_spot:'Fishing_spot.png'
};
function itemId(c){return c?.itemId||(typeof cb2ItemIds!=='undefined'?cb2ItemIds[c?.id]:null)}
function imageUrl(c){const iid=itemId(c);if(iid)return ITEM+iid+'.png';let f=imageOverrides[c.id]||((c.image||c.name).replaceAll(' ','_')+'.png');return WIKI+f;}
function fallback(c){return c.type==='Boss'?'☠️':c.type==='Monster'?'⚔️':c.type==='Skilling'?'◆':'?'}
window.cardImage=function(c,cls='cb-icon'){return `<span class="cb-img-wrap"><img class="${cls}" src="${imageUrl(c)}" alt="${c.name}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="cb2-fallback" style="display:none">${fallback(c)}</span></span>`};
if(typeof cb2Img!=='undefined')cb2Img=cardImage;
if(typeof cbImg!=='undefined')cbImg=cardImage;
// Force Collection to use the exact same real sprite renderer.
if(typeof cbCollection==='function')cbCollection=function(){return `<div class="panel"><h2>Collection</h2><div class="muted">${C.filter(c=>own(c.id)).length}/${C.length} cards discovered • ${A.filter(a=>own(a.id)).length}/${A.length} activities unlocked</div></div><div class="cb-collection">${C.map(c=>`<div class="cb-collection-card ${c.rarity} ${own(c.id)?'':'locked'}">${own(c.id)?cardImage(c,'cb-collection-icon'):'<span class="cb-unknown">?</span>'}<b>${own(c.id)?c.name:'Unknown'}</b><span class="muted">${c.rarity} • ${c.type}${c.combatStyle?` • ${c.combatStyle}`:''}<br>x${own(c.id)}</span></div>`).join('')}</div>`};
// Some newer renderers expose collectionPage instead; cover that too.
if(typeof collectionPage==='function')collectionPage=function(){return cbCollection()};
render();
})();