// Progression v2: actual OSRS-style requirements, Slayer, HP, category navigation, and reliable sprites.
const CB2_ITEM_SPRITE='https://static.runelite.net/cache/item/icon/';
const cb2State={root:'Combat',skill:'Woodcutting'};
if(!s.skills.Slayer)s.skills.Slayer=1;if(s.xp.Slayer==null)s.xp.Slayer=0;save();

const cb2ItemIds={bronze_sword:1277,steel_sword:1281,mith_scim:1329,rune_scim:1333,dragon_scim:4587,whip:4151,bronze_helm:1155,rune_helm:1163,neitiznot:10828,firecape:6570,amulet_strength:1725,glory:1704,bronze_body:1117,rune_body:1127,fighter_torso:10551,bandos:11832,wood_shield:1171,rune_kite:1201,dragon_def:12954,bronze_legs:1075,rune_legs:1079,bandos_tassets:11834,barrows_gloves:7462,dragon_boots:11840,berserker:6737,bronze_arrows:882,rune_arrows:892,bronze_axe:1351,rune_axe:1359,dragon_axe:6739,bronze_pick:1265,rune_pick:1275,dragon_pick:11920,net:303,harpoon:311,blowpipe:12926,trident:11905,bowfa:25865,twisted_bow:20997,slayer_helm:11864,serp_helm:12931,fury:6585,torture:19553,dragon_arrows:11212,dharok_body:4716,torva_body:26384,dfs:11283,ely:12817,dharok_legs:4722,torva_legs:26386,ferocious:22981,primordial:13239,lightbearer:25975,crystal_axe:23673,crystal_pick:23680,dragon_harpoon:21028,fishing_rod:307,lobster_pot:301};
const cb2ImageNames={goblin:'Goblin.png',cow:'Cow.png',giant_rat:'Giant_rat.png',guard:'Guard.png',hill_giant:'Hill_Giant.png',moss_giant:'Moss_giant.png',lesser_demon:'Lesser_demon.png',green_dragon:'Green_dragon.png',blue_dragon:'Blue_dragon.png',black_demon:'Black_demon.png',abyssal_demon:'Abyssal_demon.png',graardor:'General_Graardor.png',kraken:'Kraken.png',sarachnis:'Sarachnis.png',kbd:'King_Black_Dragon.png',zulrah:'Zulrah.png',vorkath:'Vorkath.png',muspah:'Phantom_Muspah.png',barrows:'Dharok_the_Wretched.png',normal_tree:'Tree.png',oak_tree:'Oak_tree.png',willow_tree:'Willow_tree.png',teak_tree:'Teak_tree.png',maple_tree:'Maple_tree.png',mahogany_tree:'Mahogany_tree.png',yew_tree:'Yew_tree.png',magic_tree:'Magic_tree.png',redwood_tree:'Redwood.png',copper_rock:'Copper_rock.png',tin_rock:'Tin_rock.png',iron_rock:'Iron_rock.png',coal_rock:'Coal_rock.png',gold_rock:'Gold_rock.png',mith_rock:'Mithril_rock.png',adamant_rock:'Adamantite_rock.png',runite_rock:'Runite_rock.png',amethyst:'Amethyst_crystals.png',shrimp_spot:'Fishing_spot.png',bait_spot:'Fishing_spot.png',trout_spot:'Fishing_spot.png',lobster_spot:'Fishing_spot.png',harpoon_spot:'Fishing_spot.png',monkfish_spot:'Fishing_spot.png',shark_spot:'Fishing_spot.png',angler_spot:'Fishing_spot.png'};
function cb2ImgUrl(c){if(cb2ItemIds[c.id])return `${CB2_ITEM_SPRITE}${cb2ItemIds[c.id]}.png`;const f=cb2ImageNames[c.id]||((c.image||c.name).replaceAll(' ','_')+'.png');return `https://oldschool.runescape.wiki/Special:FilePath/${encodeURIComponent(f)}`}
function cb2Img(c,cls='cb-icon'){return `<img class="${cls}" src="${cb2ImgUrl(c)}" alt="${c.name}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="cb2-fallback" style="display:none">${c.type==='Boss'?'☠':c.type==='Monster'?'⚔':c.type==='Skilling'?'◆':'?'}</span>`}

const cb2ReqCombat={bronze_sword:1,steel_sword:5,mith_scim:20,rune_scim:40,dragon_scim:60,whip:70,bronze_helm:1,steel_helm:5,rune_helm:40,neitiznot:55,slayer_helm:10,serp_helm:75,team_cape:1,firecape:1,amulet_strength:1,glory:1,fury:1,torture:75,bronze_body:1,steel_body:5,rune_body:40,fighter_torso:40,bandos:65,dharok_body:70,torva_body:80,wood_shield:1,steel_kite:5,rune_kite:40,dragon_def:60,dfs:75,ely:75,bronze_legs:1,steel_legs:5,rune_legs:40,bandos_tassets:65,dharok_legs:70,torva_legs:80,leather_gloves:1,combat_bracelet:1,barrows_gloves:1,ferocious:80,leather_boots:1,climbing_boots:1,rune_boots:40,dragon_boots:60,primordial:75,ring_dueling:1,warrior_ring:1,berserker:1,lightbearer:1,bronze_arrows:1,steel_arrows:5,rune_arrows:40,dragon_arrows:60,saradomin_sword:70,blowpipe:75,trident:75,bowfa:80,twisted_bow:85};
const cb2SkillReq={normal_tree:['Woodcutting',1],oak_tree:['Woodcutting',15],willow_tree:['Woodcutting',30],teak_tree:['Woodcutting',35],maple_tree:['Woodcutting',45],mahogany_tree:['Woodcutting',50],yew_tree:['Woodcutting',60],magic_tree:['Woodcutting',75],redwood_tree:['Woodcutting',90],copper_rock:['Mining',1],tin_rock:['Mining',1],iron_rock:['Mining',15],coal_rock:['Mining',30],gold_rock:['Mining',40],mith_rock:['Mining',55],adamant_rock:['Mining',70],runite_rock:['Mining',85],amethyst:['Mining',92],shrimp_spot:['Fishing',1],bait_spot:['Fishing',5],trout_spot:['Fishing',20],lobster_spot:['Fishing',40],harpoon_spot:['Fishing',35],monkfish_spot:['Fishing',62],shark_spot:['Fishing',76],angler_spot:['Fishing',82]};
const cb2SlayerReq={crawling_hand:5,banshee:15,rock_slug:20,cockatrice:25,pyrefiend:30,basilisk:40,fever_spider:42,infernal_mage:45,bloodveld:50,jelly:52,turoth:55,cave_horror:58,aberrant_spectre:60,dust_devil:65,kurask:70,gargoyle:75,nechryael:80,abyssal_demon:85,dark_beast:90,smoke_devil:93,alchemical_hydra:95};
const cb2MonsterHP={goblin:5,cow:8,giant_rat:5,guard:22,hill_giant:35,moss_giant:60,lesser_demon:79,green_dragon:75,blue_dragon:105,black_demon:157,abyssal_demon:150,graardor:255,kraken:255,barrows:600,sarachnis:400,kbd:240,zulrah:500,vorkath:750,muspah:850,crawling_hand:16,banshee:22,rock_slug:27,cockatrice:37,pyrefiend:45,basilisk:75,fever_spider:40,infernal_mage:60,bloodveld:120,jelly:75,turoth:75,cave_horror:55,aberrant_spectre:90,dust_devil:105,kurask:97,gargoyle:105,nechryael:105,dark_beast:220,smoke_devil:185,alchemical_hydra:1100};

const cb2MoreCards=[
['granite_maul','Granite maul','Weapon','weapon','Rare',18,50,4153],['leaf_battleaxe','Leaf-bladed battleaxe','Weapon','weapon','Epic',28,65,20727],['abyssal_dagger','Abyssal dagger','Weapon','weapon','Legendary',42,70,13265],['dragon_hunter_lance','Dragon hunter lance','Weapon','weapon','Legendary',60,70,22978],['armadyl_godsword','Armadyl godsword','Weapon','weapon','Legendary',58,75,11802],['zamorak_godsword','Zamorak godsword','Weapon','weapon','Legendary',56,75,11808],['bandos_godsword','Bandos godsword','Weapon','weapon','Legendary',56,75,11804],['occult','Occult necklace','Accessory','neck','Epic',18,70,12002],['anguish','Necklace of anguish','Accessory','neck','Legendary',22,75,19547],['barrows_helm','Dharok’s helm','Armor','head','Epic',22,70,4716],['torva_helm','Torva full helm','Armor','head','Legendary',38,80,26382],['ahrim_top','Ahrim’s robetop','Armor','body','Epic',23,70,4712],['karil_top','Karil’s leathertop','Armor','body','Epic',23,70,4736],['ahrim_skirt','Ahrim’s robeskirt','Armor','legs','Epic',20,70,4714],['karil_skirt','Karil’s leatherskirt','Armor','legs','Epic',20,70,4738],['avernic','Avernic defender','Armor','shield','Legendary',30,70,22322],['dragonfire_ward','Dragonfire ward','Armor','shield','Legendary',30,75,22003],['eternal_boots','Eternal boots','Armor','feet','Legendary',20,75,13235],['pegasian_boots','Pegasian boots','Armor','feet','Legendary',20,75,13237],['ring_suffering','Ring of suffering','Accessory','ring','Legendary',20,75,19550]
].map(x=>({id:x[0],name:x[1],type:x[2],slot:x[3],rarity:x[4],icon:'',power:x[5],reqCombat:x[6],itemId:x[7]}));
for(const c of cb2MoreCards){if(!B[c.id]){C.push(c);B[c.id]=c;cb2ItemIds[c.id]=c.itemId;cb2ReqCombat[c.id]=c.reqCombat}}

const cb2SlayerActs=[
['crawling_hand','Crawling hand','Common',5,16],['banshee','Banshee','Common',15,22],['rock_slug','Rock slug','Common',20,27],['cockatrice','Cockatrice','Uncommon',25,37],['pyrefiend','Pyrefiend','Uncommon',30,45],['basilisk','Basilisk','Uncommon',40,75],['fever_spider','Fever spider','Uncommon',42,40],['infernal_mage','Infernal mage','Rare',45,60],['bloodveld','Bloodveld','Rare',50,120],['jelly','Jelly','Rare',52,75],['turoth','Turoth','Rare',55,75],['cave_horror','Cave horror','Rare',58,55],['aberrant_spectre','Aberrant spectre','Epic',60,90],['dust_devil','Dust devil','Epic',65,105],['kurask','Kurask','Epic',70,97],['gargoyle','Gargoyle','Epic',75,105],['nechryael','Nechryael','Epic',80,105],['dark_beast','Dark beast','Legendary',90,220],['smoke_devil','Smoke devil','Legendary',93,185],['alchemical_hydra','Alchemical Hydra','Legendary',95,1100]
].map(x=>({id:x[0],name:x[1],type:x[0]==='alchemical_hydra'?'Boss':'Monster',slot:null,rarity:x[2],icon:'',power:0,kind:'Slayer',base:Math.max(8,Math.round(x[4]/2)),diff:x[3],hp:x[4],slayerReq:x[3]}));
for(const c of cb2SlayerActs){if(!B[c.id]){C.push(c);B[c.id]=c;A.push(c)}else{Object.assign(B[c.id],c)}}

for(const c of C){if(cb2ReqCombat[c.id]!=null)c.reqCombat=cb2ReqCombat[c.id];if(cb2SkillReq[c.id]){c.reqSkill=cb2SkillReq[c.id][0];c.reqLevel=cb2SkillReq[c.id][1]}}
for(const a of A){if(cb2SkillReq[a.id]){a.reqSkill=cb2SkillReq[a.id][0];a.reqLevel=cb2SkillReq[a.id][1]}if(cb2SlayerReq[a.id]){a.kind='Slayer';a.slayerReq=cb2SlayerReq[a.id];a.reqSkill='Slayer';a.reqLevel=cb2SlayerReq[a.id]}if(cb2MonsterHP[a.id])a.hp=cb2MonsterHP[a.id]}

function cb2RequirementText(x){if(x.reqCombat)return `Combat ${x.reqCombat}`;if(x.reqSkill)return `${x.reqSkill} ${x.reqLevel}`;return 'Card only'}
function cb2Meets(x){if(x.reqCombat&&s.skills.Combat<x.reqCombat)return false;if(x.reqSkill&&(s.skills[x.reqSkill]||1)<x.reqLevel)return false;return true}
function cb2FailText(x){return x.reqCombat?`Combat level ${x.reqCombat} required`:`${x.reqSkill} level ${x.reqLevel} required`}
const cb2OldEquip=equip;
equip=function(id){const c=B[id];if(!c?.slot)return;if(c.reqCombat&&s.skills.Combat<c.reqCombat)return toast(cb2FailText(c));cb2OldEquip(id)};

const cb2OldAct=act;
act=function(id){const a=A.find(x=>x.id===id);if(!a||!own(id))return;if(!cb2Meets(a))return toast(cb2FailText(a));const n=rewardFor(a);s.points+=n;s.actions++;xp(a.kind,Math.max(2,Math.round((a.hp||a.base)/4)));save();render();toast(`+${n} points`)};
const cb2OldIdle=startIdle;
startIdle=function(id){const a=A.find(x=>x.id===id);if(!a||!own(id))return;if(!cb2Meets(a))return toast(cb2FailText(a));settleIdle(false);s.idle={activityId:id,lastTick:Date.now(),totalPoints:s.idle.totalPoints||0};save();render();toast(`Now idling ${a.name}`)};

rewardFor=function(a){if(a.kind==='Combat'||a.kind==='Slayer'){const hp=a.hp||cb2MonsterHP[a.id]||50;const build=Math.max(5,cbGearPower());return Math.max(2,Math.round((hp/8)*(1+build/120)))}const tool=B[s.equipped.tool];return Math.max(1,Math.round(a.base*(1+(tool?.power||0)/20)))};
cycleSeconds=function(a){if(a.kind==='Combat'||a.kind==='Slayer'){const hp=a.hp||50;const dps=Math.max(2.5,2.5+s.skills.Combat/12+cbGearPower()/18);return Math.max(3,Math.round(hp/dps))}return Math.max(4,Math.round(5+(a.reqLevel||1)/8))};

function cb2ActivityCard(a){const unlocked=!!own(a.id),meets=cb2Meets(a),hp=(a.kind==='Combat'||a.kind==='Slayer')?` • ${a.hp||'?'} HP`:'';return `<div class="cb2-activity-card ${a.rarity} ${unlocked?'':'locked'}">${cb2Img(a,'cb-activity-icon')}<div class="cb2-grow"><b>${a.name}</b><div class="muted">${a.kind}${hp}<br>${cb2RequirementText(a)} • ${rewardFor(a)} pts • ${cycleSeconds(a)}s</div></div><div class="cb-activity-actions"><button ${unlocked&&meets?'':'disabled'} onclick="act('${a.id}')">Once</button><button class="primary" ${unlocked&&meets?'':'disabled'} onclick="startIdle('${a.id}')">${s.idle.activityId===a.id?'Idling':'Idle'}</button></div></div>`}
function cb2CombatView(){return `<div class="panel"><div class="section-head"><div><span class="eyebrow">COMBAT</span><h2>Select monster</h2></div><span class="pill">Combat ${s.skills.Combat}</span></div><div class="cb2-list">${A.filter(a=>a.kind==='Combat').sort((a,b)=>(a.hp||0)-(b.hp||0)).map(cb2ActivityCard).join('')}</div></div>`}
function cb2SkillView(){const skills=['Woodcutting','Mining','Fishing'];return `<div class="panel"><div class="cb2-catrow">${skills.map(k=>`<button class="${cb2State.skill===k?'primary':''}" onclick="cb2State.skill='${k}';render()">${k}<br><small>Lv ${s.skills[k]}</small></button>`).join('')}</div></div><div class="panel"><div class="section-head"><div><span class="eyebrow">SKILLING</span><h2>${cb2State.skill}: select resource</h2></div><span class="pill">Lv ${s.skills[cb2State.skill]}</span></div><div class="cb2-list">${A.filter(a=>a.kind===cb2State.skill).sort((a,b)=>(a.reqLevel||1)-(b.reqLevel||1)).map(cb2ActivityCard).join('')}</div></div>`}
function cb2SlayerView(){return `<div class="panel"><div class="section-head"><div><span class="eyebrow">SLAYER</span><h2>Select Slayer monster</h2></div><span class="pill">Slayer ${s.skills.Slayer}</span></div><div class="cb2-list">${A.filter(a=>a.kind==='Slayer').sort((a,b)=>(a.reqLevel||1)-(b.reqLevel||1)).map(cb2ActivityCard).join('')}</div></div>`}
function cb2Activities(){return `${cbIdlePanel()}<div class="panel"><div class="cb2-rootcats"><button class="${cb2State.root==='Combat'?'primary':''}" onclick="cb2State.root='Combat';render()">⚔<br>Combat</button><button class="${cb2State.root==='Skilling'?'primary':''}" onclick="cb2State.root='Skilling';render()">⛏<br>Skilling</button><button class="${cb2State.root==='Slayer'?'primary':''}" onclick="cb2State.root='Slayer';render()">☠<br>Slayer</button></div></div>${cb2State.root==='Combat'?cb2CombatView():cb2State.root==='Skilling'?cb2SkillView():cb2SlayerView()}`}

function cb2Bank(){const arr=filteredBank();return `<div class="panel"><div class="section-head"><div><span class="eyebrow">WORN EQUIPMENT</span><h2>Combat ${s.skills.Combat} • Power ${cbGearPower()}</h2></div><span class="pill">Slayer ${s.skills.Slayer}</span></div><div class="cb-equipment">${cbEqSlots.map(k=>{const c=B[s.equipped[k]];return `<div class="cb-eq-slot ${cbAreas[k]}" onclick="${c?`unequip('${k}')`:''}">${c?cb2Img(c,'cb-eq-icon'):`<span class="cb-empty-slot">${cbLabels[k]}</span>`}${c?`<span class="cb-eq-name">${c.name}</span>`:''}</div>`}).join('')}</div></div><div class="panel"><div class="section-head"><h2>Bank</h2><button class="danger" onclick="shredAllDuplicates()">Shred All Duplicates</button></div><div class="bank-controls"><select onchange="setBankFilter('type',this.value)"><option>All</option>${['Weapon','Armor','Accessory','Ammo','Tool'].map(x=>`<option ${bankFilters.type===x?'selected':''}>${x}</option>`).join('')}</select><select onchange="setBankFilter('rarity',this.value)"><option>All</option>${R.map(x=>`<option ${bankFilters.rarity===x?'selected':''}>${x}</option>`).join('')}</select><select onchange="setBankFilter('status',this.value)">${['All','Equipped','Unequipped','Duplicates'].map(x=>`<option ${bankFilters.status===x?'selected':''}>${x}</option>`).join('')}</select><select onchange="setBankFilter('sort',this.value)">${['Name','Power','Rarity','Quantity','Type'].map(x=>`<option ${bankFilters.sort===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="bank">${arr.map(c=>`<div class="slot ${c.rarity} ${isEquipped(c.id)?'equipped-bank':''}">${isEquipped(c.id)?'<span class="equipped-badge">EQUIPPED</span>':''}${cb2Img(c,'cb-bank-icon')}<b>${c.name}</b><span class="muted">${c.slot?cbLabels[c.slot]:c.type} • Pwr ${c.power}<br>${cb2RequirementText(c)} • x${own(c.id)}</span><button ${c.reqCombat&&s.skills.Combat<c.reqCombat?'disabled':''} onclick="${c.slot==='tool'?`s.equipped.tool='${c.id}';save();render();toast('${c.name} selected')`:`equip('${c.id}')`}">${c.slot==='tool'?'Use':'Equip'}</button>${own(c.id)>1?`<button class="danger" onclick="shred('${c.id}')">Shred 1</button>`:''}</div>`).join('')||'<div class="empty-bank">No matching cards.</div>'}</div></div>`}

const cb2OldHome=cbHome;
cbHome=function(){return `${cbIdlePanel()}<div class="hero panel"><div><span class="eyebrow">ADVENTURE LOG</span><h2>${C.filter(c=>own(c.id)).length}/${C.length} cards discovered</h2><p class="muted">Combat ${s.skills.Combat} • Slayer ${s.skills.Slayer} • ${A.filter(a=>own(a.id)).length}/${A.length} activities unlocked.</p></div><div class="hero-power"><b>${cbGearPower()}</b><span>Combat Power</span></div></div><div class="grid stats-grid"><div class="panel"><h3>⚔ Combat</h3>Lv ${s.skills.Combat}</div><div class="panel"><h3>☠ Slayer</h3>Lv ${s.skills.Slayer}</div><div class="panel"><h3>🪓 Woodcutting</h3>Lv ${s.skills.Woodcutting}</div><div class="panel"><h3>⛏ Mining</h3>Lv ${s.skills.Mining}</div><div class="panel"><h3>🎣 Fishing</h3>Lv ${s.skills.Fishing}</div></div>`};
cbActivities=cb2Activities;cbBank=cb2Bank;

const cb2OldRender=render;
render=function(){settleIdle(false);const pages={Home:cbHome,Activity:cbActivities,Packs:cbStore,Bank:cbBank,Collection:cbCollection,Forge:forge},tabs=['Home','Activity','Packs','Bank','Collection','Forge'];document.getElementById('app').innerHTML=`<div class="app"><div class="top"><div class="brand"><b>⚔ Gielinor: Cardbound</b></div><div class="wallet"><span class="pill">🪙 ${s.points.toLocaleString()}</span><span class="pill">⚔ Cmb ${s.skills.Combat}</span><span class="pill">☠ Slayer ${s.skills.Slayer}</span><span class="pill">🃏 ${C.filter(c=>own(c.id)).length}/${C.length}</span></div></div><div class="content">${pages[s.tab]()}</div><div class="tabs"><div>${tabs.map(t=>`<button class="tab ${s.tab===t?'active':''}" onclick="nav('${t}')">${{Home:'🏠',Activity:'⚔️',Packs:'🎁',Bank:'🏦',Collection:'🃏',Forge:'🔥'}[t]}<br>${t}</button>`).join('')}</div></div></div>`;cbUpdateIdleBar()};

const cb2OldPack=showPackOpening;
showPackOpening=function(name,cards){let idx=0,revealed=false;const m=document.createElement('div');m.className='modal pack-modal';document.body.append(m);function draw(){const c=cards[idx],remaining=cards.length-idx-1;m.innerHTML=`<div class="pack-stage"><div class="pack-topline"><b>${name} Pack</b><span>${idx+1}/${cards.length}</span></div><div class="stack-wrap" id="packTap">${Array.from({length:Math.min(4,remaining)}).map((_,i)=>`<div class="card-back ghost" style="transform:translate(${(i+1)*4}px,${-(i+1)*4}px) rotate(${(i%2?1:-1)*(i+1)}deg)"></div>`).join('')}<div class="reveal-card ${revealed?'revealed':''} ${c.rarity}"><div class="card-face back-face"><div class="rune-mark">⚔</div><b>GIELINOR</b><small>CARDBOUND</small><div class="tap-hint">Tap to reveal</div></div><div class="card-face front-face"><div class="rarity-tag">${c.rarity}</div>${cb2Img(c,'cb-pack-icon')}<h2>${c.name}</h2><div class="card-type">${c.type}</div><div class="muted">${cb2RequirementText(c)}</div>${c.power?`<div class="statline">Power +${c.power}</div>`:''}<div class="ownedline">Owned ×${own(c.id)}</div><div class="tap-hint">${idx===cards.length-1?'Tap for results':'Tap for next card'}</div></div></div></div><div class="pack-progress">${cards.map((_,i)=>`<span class="${i<idx?'done':i===idx?'current':''}"></span>`).join('')}</div></div>`;m.querySelector('#packTap').onclick=()=>{if(!revealed){revealed=true;draw();return}if(idx<cards.length-1){idx++;revealed=false;draw()}else results()}}function results(){m.innerHTML=`<div class="pack-results"><h2>${name} Pack Results</h2><div class="results-grid">${cards.map(c=>`<div class="result-card ${c.rarity}">${cb2Img(c,'cb-result-icon')}<b>${c.name}</b><div class="muted">${c.rarity} • ${c.type}<br>${cb2RequirementText(c)} • Owned ×${own(c.id)}</div></div>`).join('')}</div><button class="primary wide" onclick="this.closest('.modal').remove()">Add to Bank</button></div>`}draw()};

save();render();