// Sailing UI: nested Sailing -> activity type -> facility-gated action list.
(function(){
const priorRender=render;
window.cbSailingUi={category:null};
window.cbSailingOpen=cat=>{cbSailingUi.category=cat;render()};
window.cbSailingBack=()=>{cbSailingUi.category=null;render()};
const img=(c,cls='cb-sailing-img')=>typeof cardImage==='function'?cardImage(c,cls):`<span>${c.icon||'⚓'}</span>`;
function shell(content){const tabs=['Home','Activity','Packs','Bank','Collection','Forge'];return `<div class="app"><div class="top"><div class="brand">⚔️ <b>Gielinor: Cardbound</b></div><div class="wallet"><span class="pill">🪙 ${s.points.toLocaleString()} points</span><span class="pill">💥 Power ${Math.round(power())}</span><span class="pill">🃏 ${C.filter(c=>own(c.id)).length}/${C.length}</span></div></div><div class="content">${content}</div><div class="tabs"><div>${tabs.map(t=>`<button class="tab ${s.tab===t?'active':''}" onclick="nav('${t}')">${{Home:'🏠',Activity:'⚔️',Packs:'🎁',Bank:'🏦',Collection:'🃏',Forge:'🔥'}[t]}<br>${t}</button>`).join('')}</div></div></div>`}
function sailingHome(){const categories=cbSailingCategories||[];return `${typeof cbIdlePanel==='function'?cbIdlePanel():''}<div class="panel"><button class="secondary" onclick="cbSailingUi.category=null;cbCoreUi.activityRoot=null;render()">← Activities</button><div class="section-head"><div><span class="eyebrow">SAILING</span><h2>Captain your ship</h2></div><span class="pill">Lv ${s.skills.Sailing||1}</span></div><p class="muted">Choose a Sailing method. Activities require both the activity card and the appropriate boat/facility cards.</p><div class="cb-sailing-categories">${categories.map(cat=>{const count=A.filter(a=>a.kind==='Sailing'&&a.sailingCategory===cat).length;return `<button class="cb-sailing-category" onclick="cbSailingOpen('${cat}')"><span>${{Port Tasks:'📜',Charting:'🗺️',Salvaging:'🪝',Trawling:'🐟',Combat:'💥',Trials:'🏁'}[cat]||'⚓'}</span><b>${cat}</b><small>${count} actions</small></button>`}).join('')}</div></div>${facilitySummary()}`}
function facilitySummary(){const cards=C.filter(c=>c.type==='Sailing Facility');const owned=cards.filter(c=>own(c.id));return `<div class="panel"><div class="section-head"><div><span class="eyebrow">SHIP FACILITIES</span><h3>${owned.length}/${cards.length} unlocked</h3></div></div><div class="cb-sailing-facilities">${cards.map(c=>`<div class="cb-sailing-facility ${c.rarity} ${own(c.id)?'':'locked'}">${img(c,'cb-sailing-facility-img')}<b>${c.name}</b><small>Sailing ${c.reqLevel}${own(c.id)?' • Owned':' • Card required'}</small></div>`).join('')}</div></div>`}
function categoryPage(cat){const acts=A.filter(a=>a.kind==='Sailing'&&a.sailingCategory===cat);return `${typeof cbIdlePanel==='function'?cbIdlePanel():''}<div class="panel"><button class="secondary" onclick="cbSailingBack()">← Sailing</button><div class="section-head"><div><span class="eyebrow">SAILING • ${cat.toUpperCase()}</span><h2>${cat}</h2></div><span class="pill">Lv ${s.skills.Sailing||1}</span></div><div class="cb2-activity-list">${acts.map(a=>{const unlocked=own(a.id)>0,meets=cbSailingReqMet(a),active=s.idle.activityId===a.id,req=(a.reqCards||[]).map(id=>B[id]?.name||id).join(', ');return `<div class="cb2-activity-card ${a.rarity} ${unlocked?'':'locked'} ${active?'idle-selected':''}">${img(a,'cb-activity-icon')}<div class="cb2-grow"><b>${a.name}</b><div class="muted">Sailing ${a.reqLevel} • ${rewardFor(a)} pts • ${cycleSeconds(a)}s<br>${req?`Facility: ${req}<br>`:''}${!unlocked?'Activity card required':meets?'Ready':'Missing facility/level requirement'}</div></div><div class="cb2-actions"><button ${unlocked&&meets?'':'disabled'} onclick="act('${a.id}')">Once</button><button class="${active?'danger':'primary'}" ${unlocked&&meets?'':'disabled'} onclick="${active?'stopIdle()':`startIdle('${a.id}')`}">${active?'Stop':'Idle'}</button></div></div>`}).join('')}</div></div>`}
const oldCbSetActivityRoot=window.cbSetActivityRoot;
window.cbSetActivityRoot=function(root){if(root==='Sailing'){cbCoreUi.activityRoot='Sailing';cbSailingUi.category=null;render();return}oldCbSetActivityRoot(root)};
// Inject Sailing into the core Activity root and Home without rewriting the existing renderer.
render=function(){
  if(s.tab==='Activity'&&window.cbCoreUi?.activityRoot==='Sailing'){document.getElementById('app').innerHTML=shell(cbSailingUi.category?categoryPage(cbSailingUi.category):sailingHome());return;}
  priorRender();
  if(s.tab==='Activity'&&!window.cbCoreUi?.activityRoot){const root=document.querySelector('.cbcore-root-grid');if(root&&!root.querySelector('[data-sailing-root]'))root.insertAdjacentHTML('beforeend',`<button data-sailing-root class="cbcore-root-card" onclick="cbSetActivityRoot('Sailing')"><span>⛵</span><b>Sailing</b><small>Level ${s.skills.Sailing||1}</small></button>`);}
  if(s.tab==='Home'){const stats=document.querySelector('.stats-grid');if(stats&&!stats.querySelector('[data-sailing-home]'))stats.insertAdjacentHTML('afterbegin',`<button data-sailing-home class="panel" onclick="s.tab='Activity';cbSetActivityRoot('Sailing')"><h3>⛵ Sailing</h3>Level ${s.skills.Sailing||1}<br><span class="muted">Facilities ${C.filter(c=>c.type==='Sailing Facility'&&own(c.id)).length}/${C.filter(c=>c.type==='Sailing Facility').length}</span></button>`);}
};
render();
})();