// Final UI pass: explicit Melee/Ranged/Magic on Home + Activity, plus escalating pack presentation.
(function(){
const STYLES=['Melee','Ranged','Magic'];
function stIcon(st){return st==='Melee'?'⚔️':st==='Ranged'?'🏹':'✨'}
function equippedStyle(){return B[s.equipped.weapon]?.combatStyle||'Melee'}
function stPower(st){return 5+Object.entries(s.equipped).filter(([slot,id])=>id&&slot!=='tool').reduce((n,[,id])=>{const c=B[id];if(!c)return n;return n+(c.power||0)*((c.combatStyle||'Melee')===st?1:.25)},0)}
function homeV11(){return `${typeof cbIdlePanel==='function'?cbIdlePanel():''}<div class="panel"><span class="eyebrow">COMBAT STYLES</span><h2>Combat Progression</h2><div class="cb11-combat-grid">${STYLES.map(st=>`<button class="cb11-style-card" onclick="cb2State.root='${st}';s.tab='Activity';render()"><span>${stIcon(st)}</span><b>${st}</b><small>Lv ${s.skills[st]||1} • Power ${Math.round(stPower(st))}</small></button>`).join('')}</div></div><div class="grid stats-grid"><div class="panel"><h3>☠ Slayer</h3>Lv ${s.skills.Slayer||1}</div><div class="panel"><h3>🪓 Woodcutting</h3>Lv ${s.skills.Woodcutting||1}</div><div class="panel"><h3>⛏ Mining</h3>Lv ${s.skills.Mining||1}</div><div class="panel"><h3>🎣 Fishing</h3>Lv ${s.skills.Fishing||1}</div></div><div class="hero panel"><div><span class="eyebrow">ADVENTURE LOG</span><h2>${C.filter(c=>own(c.id)).length}/${C.length} cards discovered</h2><p class="muted">${A.filter(a=>own(a.id)).length}/${A.length} activities unlocked.</p></div></div>`}
function rootActivity(){return `${typeof cbIdlePanel==='function'?cbIdlePanel():''}<div class="panel"><span class="eyebrow">ACTIVITY</span><h2>Choose an activity</h2><div class="cb11-root-grid"><button class="cb11-root-card" onclick="cb2State.root='Melee';render()"><b>⚔️ Melee</b><span class="muted">Lv ${s.skills.Melee||1}</span></button><button class="cb11-root-card" onclick="cb2State.root='Ranged';render()"><b>🏹 Ranged</b><span class="muted">Lv ${s.skills.Ranged||1}</span></button><button class="cb11-root-card" onclick="cb2State.root='Magic';render()"><b>✨ Magic</b><span class="muted">Lv ${s.skills.Magic||1}</span></button><button class="cb11-root-card" onclick="cb2State.root='Slayer';render()"><b>☠ Slayer</b><span class="muted">Lv ${s.skills.Slayer||1}</span></button><button class="cb11-root-card" onclick="cb2State.root='Skilling';render()"><b>🛠 Skilling</b><span class="muted">Woodcutting • Mining • Fishing</span></button></div></div>`}
function combatBranch(st){const current=equippedStyle(),acts=A.filter(a=>a.kind==='Combat');return `${typeof cbIdlePanel==='function'?cbIdlePanel():''}<div class="panel"><button class="secondary cb11-back" onclick="cb2State.root='Root';render()">← Activities</button><div class="section-head"><div><span class="eyebrow">${st.toUpperCase()}</span><h2>${st} Combat</h2></div><span class="pill">Lv ${s.skills[st]||1}</span></div><div class="cb11-style-note">${current===st?`Equipped for ${st}.`:`Equip a ${st.toLowerCase()} weapon in Bank to fight with this style.`} • Power ${Math.round(stPower(st))}</div><div class="cb2-activity-list">${acts.map(a=>{const unlocked=!!own(a.id),meets=cb2Meets(a),usable=current===st&&unlocked&&meets;return `<div class="cb2-activity-card ${a.rarity} ${unlocked?'':'locked'}">${typeof cardImage==='function'?cardImage(a,'cb-activity-icon'):cb2Img(a,'cb-activity-icon')}<div class="cb2-grow"><b>${a.name}</b><div class="muted">${a.hp||'?'} HP • ${rewardFor(a)} pts • ${cycleSeconds(a)}s<br>${unlocked?(meets?'Card unlocked':'Requirements not met'):'Card required'}</div></div><div class="cb2-actions"><button ${usable?'':'disabled'} onclick="act('${a.id}')">Once</button><button class="primary" ${usable?'':'disabled'} onclick="startIdle('${a.id}')">Idle</button></div></div>`}).join('')}</div></div>`}
const oldActivity=activityPage;
activityPage=function(){if(!cb2State.root||cb2State.root==='Combat'||cb2State.root==='Root')return rootActivity();if(STYLES.includes(cb2State.root))return combatBranch(cb2State.root);return oldActivity()};
home=homeV11;if(typeof cbHome==='function')cbHome=homeV11;
const packMeta={Beginner:{icon:'📜',tag:'Worn adventurer cache',desc:'A humble start to your collection.'},Bronze:{icon:'🟤',tag:'Forged bronze cache',desc:'Sturdier pulls with improved uncommon odds.'},Rune:{icon:'🔷',tag:'Runic vault pack',desc:'Runic energy surrounds stronger equipment and rare cards.'},Dragon:{icon:'🐉',tag:'Dragonfire reliquary',desc:'A high-tier pack with a serious chance at epic rewards.'},Raid:{icon:'👑',tag:'Ancient raid reliquary',desc:'The most prestigious pack, built around endgame pulls.'}};
function storeV11(){return `<div class="panel pack-banner"><span class="eyebrow">PACK SHOP</span><h2>Card Packs</h2><p class="muted">Higher tiers look and feel more prestigious while also improving rarity odds.</p></div><div class="cb11-pack-grid">${Object.entries(packs).map(([n,p])=>{const m=packMeta[n]||packMeta.Beginner;return `<div class="cb11-pack pack-${n}"><div class="cb11-pack-art">${m.icon}</div><span class="eyebrow">${m.tag}</span><h3>${n} Pack</h3><div class="muted">${m.desc}<br>${p.n} cards • ${p.cost.toLocaleString()} pts • Legendary ${p.o[4]}%</div><button class="primary wide" onclick="openPack('${n}')">Buy & Open</button></div>`}).join('')}</div>`}
store=storeV11;if(typeof cbStore==='function')cbStore=storeV11;
const oldShow=showPackOpening;
showPackOpening=function(name,cards){oldShow(name,cards);requestAnimationFrame(()=>{const stage=document.querySelector('.pack-modal .pack-stage');if(stage)stage.classList.add('pack-'+name);const top=stage?.querySelector('.pack-topline b');if(top){const m=packMeta[name]||packMeta.Beginner;top.textContent=`${m.icon} ${name} Pack`}})};
cb2State.root='Root';save();render();
})();