const CB_WIKI='https://oldschool.runescape.wiki/Special:FilePath/';
const cbEsc=s=>encodeURIComponent((s||'').replaceAll(' ','_')+'.png');
const cbImgUrl=c=>CB_WIKI+cbEsc(c.image||c.name);
const cbImg=(c,cls='cb-icon')=>`<img class="${cls}" src="${cbImgUrl(c)}" alt="${c.name}" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span class="cb-fallback" style="display:none">${c.type==='Boss'?'☠':c.type==='Monster'?'⚔':'◆'}</span>`;
const cbEqSlots=['head','cape','neck','ammo','weapon','body','shield','legs','hands','feet','ring'];
const cbLabels={head:'Head',cape:'Cape',neck:'Neck',ammo:'Ammo',weapon:'Weapon',body:'Body',shield:'Shield',legs:'Legs',hands:'Gloves',feet:'Boots',ring:'Ring',tool:'Tool'};
const cbAreas={head:'cb-head',cape:'cb-cape',neck:'cb-neck',ammo:'cb-ammo',weapon:'cb-weapon',body:'cb-body',shield:'cb-shield',legs:'cb-legs',hands:'cb-hands',feet:'cb-feet',ring:'cb-ring'};
const cbExtraCards=[
['iron_sword','Iron sword','Weapon','weapon','Common',3],['adamant_scim','Adamant scimitar','Weapon','weapon','Uncommon',11],['saradomin_sword','Saradomin sword','Weapon','weapon','Epic',32],['blowpipe','Toxic blowpipe','Weapon','weapon','Legendary',46],['trident','Trident of the seas','Weapon','weapon','Epic',34],['bowfa','Bow of faerdhinen','Weapon','weapon','Legendary',55],['twisted_bow','Twisted bow','Weapon','weapon','Legendary',65],
['steel_helm','Steel full helm','Armor','head','Common',4],['slayer_helm','Slayer helmet','Armor','head','Epic',22],['serp_helm','Serpentine helm','Armor','head','Legendary',30],['obsidian_cape','Obsidian cape','Accessory','cape','Uncommon',5],['ava','Ava’s accumulator','Accessory','cape','Rare',10],['assembler','Ava’s assembler','Accessory','cape','Legendary',20],['amulet_power','Amulet of power','Accessory','neck','Uncommon',5],['fury','Amulet of fury','Accessory','neck','Epic',14],['torture','Amulet of torture','Accessory','neck','Legendary',20],['steel_arrows','Steel arrow','Ammo','ammo','Common',2],['dragon_arrows','Dragon arrow','Ammo','ammo','Epic',13],['steel_body','Steel platebody','Armor','body','Common',5],['dharok_body','Dharok’s platebody','Armor','body','Epic',24],['torva_body','Torva platebody','Armor','body','Legendary',48],['steel_kite','Steel kiteshield','Armor','shield','Common',4],['dfs','Dragonfire shield','Armor','shield','Legendary',30],['ely','Elysian spirit shield','Armor','shield','Legendary',45],['steel_legs','Steel platelegs','Armor','legs','Common',4],['dharok_legs','Dharok’s platelegs','Armor','legs','Epic',21],['torva_legs','Torva platelegs','Armor','legs','Legendary',42],['combat_bracelet','Combat bracelet','Armor','hands','Rare',7],['ferocious','Ferocious gloves','Armor','hands','Legendary',22],['climbing_boots','Climbing boots','Armor','feet','Uncommon',3],['rune_boots','Rune boots','Armor','feet','Rare',8],['primordial','Primordial boots','Armor','feet','Legendary',21],['warrior_ring','Warrior ring','Accessory','ring','Rare',7],['lightbearer','Lightbearer','Accessory','ring','Legendary',18],['steel_axe','Steel axe','Tool','tool','Common',3],['mithril_axe','Mithril axe','Tool','tool','Uncommon',5],['crystal_axe','Crystal axe','Tool','tool','Legendary',20],['steel_pick','Steel pickaxe','Tool','tool','Common',3],['mithril_pick','Mithril pickaxe','Tool','tool','Uncommon',5],['crystal_pick','Crystal pickaxe','Tool','tool','Legendary',20],['fishing_rod','Fishing rod','Tool','tool','Common',2],['lobster_pot','Lobster pot','Tool','tool','Uncommon',4],['dragon_harpoon','Dragon harpoon','Tool','tool','Epic',13]
].map(x=>({id:x[0],name:x[1],type:x[2],slot:x[3],rarity:x[4],icon:'',power:x[5]}));
const cbExtraActs=[
['giant_rat','Giant rat','Monster','Common','Combat',6,4],['guard','Guard','Monster','Common','Combat',8,6],['moss_giant','Moss giant','Monster','Uncommon','Combat',20,16],['lesser_demon','Lesser demon','Monster','Uncommon','Combat',28,22],['blue_dragon','Blue dragon','Monster','Rare','Combat',55,38],['black_demon','Black demon','Monster','Rare','Combat',65,45],['kraken','Kraken','Boss','Epic','Combat',120,60],['barrows','Barrows','Boss','Epic','Combat',145,68],['sarachnis','Sarachnis','Boss','Epic','Combat',165,72],['kbd','King Black Dragon','Boss','Epic','Combat',190,78],['zulrah','Zulrah','Boss','Legendary','Combat',310,105],['vorkath','Vorkath','Boss','Legendary','Combat',360,112],['muspah','Phantom Muspah','Boss','Legendary','Combat',420,120],
['teak_tree','Teak tree','Skilling','Uncommon','Woodcutting',19,14],['maple_tree','Maple tree','Skilling','Rare','Woodcutting',25,18],['mahogany_tree','Mahogany tree','Skilling','Rare','Woodcutting',30,22],['redwood_tree','Redwood tree','Skilling','Legendary','Woodcutting',105,45],['tin_rock','Tin rock','Skilling','Common','Mining',4,1],['gold_rock','Gold rocks','Skilling','Uncommon','Mining',22,14],['adamant_rock','Adamantite rocks','Skilling','Rare','Mining',55,28],['amethyst','Amethyst crystals','Skilling','Legendary','Mining',110,46],['bait_spot','Bait fishing spot','Skilling','Common','Fishing',7,4],['trout_spot','Lure fishing spot','Skilling','Common','Fishing',9,5],['monkfish_spot','Monkfish fishing spot','Skilling','Rare','Fishing',45,24],['angler_spot','Anglerfish fishing spot','Skilling','Legendary','Fishing',100,44]
].map(x=>({id:x[0],name:x[1],type:x[2],slot:null,rarity:x[3],icon:'',power:0,kind:x[4],base:x[5],diff:x[6]}));
for(const c of [...cbExtraCards,...cbExtraActs]){if(!B[c.id]){C.push(c);B[c.id]=c;if(c.kind)A.push(c)}}
function cbGearPower(){return 5+cbEqSlots.map(k=>s.equipped[k]).filter(Boolean).reduce((n,id)=>n+(B[id]?.power||0),0)}
function cbToolId(){return s.equipped.tool||null}
function cbIdlePanel(){const a=A.find(x=>x.id===s.idle.activityId);if(!a)return '';return `<div class="panel cb-idle"><div class="cb-idle-head">${cbImg(a,'cb-activity-icon')}<div><span class="eyebrow">IDLE ACTIVITY</span><h3>${a.name}</h3><div class="muted">${a.kind} • ${rewardFor(a)} pts every ${cycleSeconds(a)}s • ~${Math.round(rewardFor(a)*3600/cycleSeconds(a)).toLocaleString()} pts/hr</div></div><button class="danger" onclick="stopIdle()">Stop</button></div><div class="cb-cycle-track"><div class="cb-cycle-fill" id="cbCycleFill"></div></div><div class="cb-cycle-meta"><span id="cbCycleText">Working…</span><span>8h offline cap</span></div></div>`}
function cbUpdateIdleBar(){const a=A.find(x=>x.id===s.idle.activityId),f=document.getElementById('cbCycleFill'),t=document.getElementById('cbCycleText');if(!a||!f||!t)return;const ms=cycleSeconds(a)*1000,elapsed=Math.max(0,Date.now()-s.idle.lastTick),p=(elapsed%ms)/ms*100;f.style.width=p+'%';t.textContent=`${p.toFixed(0)}% • ${(Math.max(0,ms-(elapsed%ms))/1000).toFixed(1)}s to next reward`}
function cbEqSlot(k){const c=B[s.equipped[k]];return `<div class="cb-eq-slot ${cbAreas[k]}" onclick="${c?`unequip('${k}')`:''}">${c?cbImg(c,'cb-eq-icon'):`<span class="cb-empty-slot">${cbLabels[k]}</span>`}${c?`<span class="cb-eq-name">${c.name}</span>`:''}</div>`}
function cbBank(){const arr=filteredBank();const tool=B[cbToolId()];return `<div class="panel"><div class="section-head"><div><span class="eyebrow">WORN EQUIPMENT</span><h2>Combat Power ${cbGearPower()}</h2></div><span class="pill">${cbEqSlots.filter(k=>s.equipped[k]).length}/11</span></div><div class="cb-equipment">${cbEqSlots.map(cbEqSlot).join('')}</div><div class="cb-tool"><span class="eyebrow">ACTIVE SKILLING TOOL</span><div>${tool?cbImg(tool,'cb-eq-icon'):''}<b>${tool?.name||'None selected'}</b><span class="muted">${tool?`Power ${tool.power}`:'Choose a tool from the bank'}</span></div></div></div><div class="panel"><div class="section-head"><h2>Bank</h2><button class="danger" onclick="shredAllDuplicates()">Shred All Duplicates</button></div><div class="bank-controls"><select onchange="setBankFilter('type',this.value)"><option>All</option>${['Weapon','Armor','Accessory','Ammo','Tool'].map(x=>`<option ${bankFilters.type===x?'selected':''}>${x}</option>`).join('')}</select><select onchange="setBankFilter('rarity',this.value)"><option>All</option>${R.map(x=>`<option ${bankFilters.rarity===x?'selected':''}>${x}</option>`).join('')}</select><select onchange="setBankFilter('status',this.value)">${['All','Equipped','Unequipped','Duplicates'].map(x=>`<option ${bankFilters.status===x?'selected':''}>${x}</option>`).join('')}</select><select onchange="setBankFilter('sort',this.value)">${['Name','Power','Rarity','Quantity','Type'].map(x=>`<option ${bankFilters.sort===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="bank">${arr.map(c=>`<div class="slot ${c.rarity} ${isEquipped(c.id)?'equipped-bank':''}">${isEquipped(c.id)?'<span class="equipped-badge">EQUIPPED</span>':''}${cbImg(c,'cb-bank-icon')}<b>${c.name}</b><span class="muted">${cbLabels[c.slot]} • Pwr ${c.power}<br>x${own(c.id)}${own(c.id)>1?` • +${own(c.id)-1} dupes`:''}</span><button onclick="${c.slot==='tool'?`s.equipped.tool='${c.id}';save();render();toast('${c.name} selected')`:`equip('${c.id}')`}">${c.slot==='tool'?'Use':'Equip'}</button>${own(c.id)>1?`<button class="danger" onclick="shred('${c.id}')">Shred 1</button>`:''}</div>`).join('')||'<div class="empty-bank">No matching cards.</div>'}</div></div>`}
function cbActivities(){return `${cbIdlePanel()}${['Combat','Woodcutting','Mining','Fishing'].map(k=>`<div class="panel"><div class="section-head"><h2>${k}</h2><span class="pill">Lv ${s.skills[k]}</span></div><div class="cb-activity-list">${A.filter(a=>a.kind===k).map(a=>`<div class="cb-activity-row ${own(a.id)?'':'locked'} ${a.rarity}">${cbImg(a,'cb-activity-icon')}<div><b>${a.name}</b><div class="muted">${own(a.id)?`${rewardFor(a)} pts • ${cycleSeconds(a)}s cycle • Req ${need(a)}`:'Card required'}</div></div><div class="cb-activity-actions"><button ${own(a.id)?'':'disabled'} onclick="act('${a.id}')">Once</button><button class="primary" ${own(a.id)?'':'disabled'} onclick="startIdle('${a.id}')">${s.idle.activityId===a.id?'Idling':'Idle'}</button></div></div>`).join('')}</div></div>`).join('')}`}
function cbCollection(){return `<div class="panel"><h2>Collection</h2><div class="muted">${C.filter(c=>own(c.id)).length}/${C.length} cards discovered • ${A.filter(a=>own(a.id)).length}/${A.length} activities unlocked</div></div><div class="cb-collection">${C.map(c=>`<div class="cb-collection-card ${c.rarity} ${own(c.id)?'':'locked'}">${own(c.id)?cbImg(c,'cb-collection-icon'):'<span class="cb-unknown">?</span>'}<b>${own(c.id)?c.name:'Unknown'}</b><span class="muted">${c.rarity} • ${c.type}<br>x${own(c.id)}</span></div>`).join('')}</div>`}
function cbHome(){return `${cbIdlePanel()}<div class="hero panel"><div><span class="eyebrow">ADVENTURE LOG</span><h2>${C.filter(c=>own(c.id)).length}/${C.length} cards discovered</h2><p class="muted">${A.filter(a=>own(a.id)).length}/${A.length} combat and skilling activities unlocked.</p></div><div class="hero-power"><b>${cbGearPower()}</b><span>Combat Power</span></div></div><div class="grid stats-grid"><div class="panel"><h3>⚔ Combat</h3>Lv ${s.skills.Combat}</div><div class="panel"><h3>🪓 Woodcutting</h3>Lv ${s.skills.Woodcutting}</div><div class="panel"><h3>⛏ Mining</h3>Lv ${s.skills.Mining}</div><div class="panel"><h3>🎣 Fishing</h3>Lv ${s.skills.Fishing}</div></div>`}
function cbStore(){return `<div class="panel pack-banner"><span class="eyebrow">PACK SHOP</span><h2>Choose your booster</h2><p class="muted">${C.length} cards are currently available.</p></div><div class="grid">${Object.entries(packs).map(([n,p])=>`<div class="card pack-card"><div class="pack-art">🎴</div><b>${n} Pack</b><div class="muted">${p.n} cards • ${p.cost.toLocaleString()} pts<br>Legendary ${p.o[4]}%</div><button class="primary" onclick="openPack('${n}')">Buy & Open</button></div>`).join('')}</div>`}
const cbOldShowPack=showPackOpening;
showPackOpening=function(name,cards){let idx=0,revealed=false;const m=document.createElement('div');m.className='modal pack-modal';document.body.append(m);function draw(){const c=cards[idx],remaining=cards.length-idx-1;m.innerHTML=`<div class="pack-stage"><div class="pack-topline"><b>${name} Pack</b><span>${idx+1}/${cards.length}</span></div><div class="stack-wrap" id="packTap">${Array.from({length:Math.min(4,remaining)}).map((_,i)=>`<div class="card-back ghost" style="transform:translate(${(i+1)*4}px,${-(i+1)*4}px) rotate(${(i%2?1:-1)*(i+1)}deg)"></div>`).join('')}<div class="reveal-card ${revealed?'revealed':''} ${c.rarity}"><div class="card-face back-face"><div class="rune-mark">⚔</div><b>GIELINOR</b><small>CARDBOUND</small><div class="tap-hint">Tap to reveal</div></div><div class="card-face front-face"><div class="rarity-tag">${c.rarity}</div>${cbImg(c,'cb-pack-icon')}<h2>${c.name}</h2><div class="card-type">${c.type}${c.slot?` • ${cbLabels[c.slot]}`:''}</div>${c.power?`<div class="statline">Power +${c.power}</div>`:''}<div class="ownedline">Owned ×${c.count}</div><div class="tap-hint">${idx===cards.length-1?'Tap for results':'Tap for next card'}</div></div></div></div><div class="pack-progress">${cards.map((_,i)=>`<span class="${i<idx?'done':i===idx?'current':''}"></span>`).join('')}</div><button class="secondary" onclick="this.closest('.modal').remove()">Skip opening</button></div>`;m.querySelector('#packTap').onclick=()=>{if(!revealed){revealed=true;draw()}else if(idx<cards.length-1){idx++;revealed=false;draw()}else results()}}function results(){m.innerHTML=`<div class="pack-results"><h2>${name} Pack Results</h2><div class="results-grid">${cards.map(c=>`<div class="result-card ${c.rarity}">${cbImg(c,'cb-result-icon')}<b>${c.name}</b><div class="muted">${c.rarity} • ${c.type}<br>Owned ×${c.count}</div></div>`).join('')}</div><button class="primary wide" onclick="this.closest('.modal').remove()">Add to Bank</button></div>`}draw()};
render=function(){const pages={Home:cbHome,Activity:cbActivities,Packs:cbStore,Bank:cbBank,Collection:cbCollection,Forge:forge},tabs=['Home','Activity','Packs','Bank','Collection','Forge'];document.getElementById('app').innerHTML=`<div class="app"><div class="top"><div class="brand"><b>Gielinor: Cardbound</b></div><div class="wallet"><span class="pill">🪙 ${s.points.toLocaleString()}</span><span class="pill">⚔ ${cbGearPower()}</span><span class="pill">🃏 ${C.filter(c=>own(c.id)).length}/${C.length}</span></div></div><div class="content">${pages[s.tab]()}</div><div class="tabs"><div>${tabs.map(t=>`<button class="tab ${s.tab===t?'active':''}" onclick="nav('${t}')">${({Home:'🏠',Activity:'⚒',Packs:'🎁',Bank:'🏦',Collection:'🃏',Forge:'🔥'})[t]}<br>${t}</button>`).join('')}</div></div></div>`;cbUpdateIdleBar()};
setInterval(cbUpdateIdleBar,250);render();